aceh_urls = {
    "https://id.wikipedia.org/wiki/Rencong",
    "https://id.wikipedia.org/wiki/Tari_Saman",
    "https://id.wikipedia.org/wiki/Didong",
    "https://id.wikipedia.org/wiki/Kerawang_Gayo",
    "https://id.wikipedia.org/wiki/Tari_Seudati",
    "https://id.wikipedia.org/wiki/Rumah_adat_Aceh",
    "https://id.wikipedia.org/wiki/Kopiah_Riman",
    "https://id.wikipedia.org/wiki/Tari_Rapa%27i_Geleng",
    "https://id.wikipedia.org/wiki/Tari_Dampeng",
    "https://id.wikipedia.org/wiki/Tari_Bines",
    "https://id.wikipedia.org/wiki/Pinto_Aceh",
    "https://id.wikipedia.org/wiki/Tari_Rabbani_Wahid",
    "https://id.wikipedia.org/wiki/Mak_Meugang",
    "https://id.wikipedia.org/wiki/Nandong",
    "https://id.wikipedia.org/wiki/Guel",
    "https://id.wikipedia.org/wiki/Tari_Likok_Pulo",
    "https://id.wikipedia.org/wiki/Pacu_Kude",
    "https://id.wikipedia.org/wiki/Menatakhken_Hinei",
    "https://id.wikipedia.org/wiki/Canang_Kayu",
    "https://id.wikipedia.org/wiki/Maracu",
    "https://id.wikipedia.org/wiki/Landok_Sampot",
    "https://id.wikipedia.org/wiki/Rapai_Pase",
    "https://id.wikipedia.org/wiki/Payung_Mesikhat",
    "https://id.wikipedia.org/wiki/Pasenatken",
    "https://id.wikipedia.org/wiki/Rapa%27i_Geurimpheng",
    "https://id.wikipedia.org/wiki/Keumamah",
    "https://id.wikipedia.org/wiki/Laweut",
    "https://id.wikipedia.org/wiki/Likee",
    "https://id.wikipedia.org/wiki/Panglima_Laot",
    "https://id.wikipedia.org/wiki/Kuah_Beulangong",
    "https://id.wikipedia.org/wiki/Keni_Gayo",
    "https://id.wikipedia.org/wiki/Pemamanan",
    "https://id.wikipedia.org/wiki/Gutel",
    "https://id.wikipedia.org/wiki/Sining",
    "https://id.wikipedia.org/wiki/Silat_Pelintau",
    "https://id.wikipedia.org/wiki/Peusijuek",
    "https://id.wikipedia.org/wiki/Keuneunong",
    "https://id.wikipedia.org/wiki/Tari_Rapa%27i_Bubee",
    "https://id.wikipedia.org/wiki/Kupiah_meukeutob",
    "https://id.wikipedia.org/wiki/Sie_Reuboh",
    "https://id.wikipedia.org/wiki/Tangis_Dilo",
    "https://id.wikipedia.org/wiki/Bahasa_Devayan"
}

sumatera_utara_urls = {
    "https://id.wikipedia.org/wiki/Tor-Tor",
    "https://id.wikipedia.org/wiki/Gordang_Sambilan",
    "https://id.wikipedia.org/wiki/Siwaluh_Jabu",
    "https://id.wikipedia.org/wiki/Huda-huda",
    "https://id.wikipedia.org/wiki/Omo_Hada",
    "https://id.wikipedia.org/wiki/Bola_Nafo",
    "https://id.wikipedia.org/wiki/Tari_Serampang_12",
    "https://id.wikipedia.org/wiki/Berahoi",
    "https://id.wikipedia.org/wiki/Merdang-Merdem",
    "https://id.wikipedia.org/wiki/Ulos_Batak_Toba",
    "https://id.wikipedia.org/wiki/Pustaha_Lak-Lak",
    "https://id.wikipedia.org/wiki/Erpangir_Ku_Lau",
    "https://id.wikipedia.org/wiki/Parmalim",
    "https://id.wikipedia.org/wiki/Ni_%27Oworu",
    "https://id.wikipedia.org/wiki/Dayok_Binatur",
    "https://id.wikipedia.org/wiki/Genderang_sisibah",
    "https://id.wikipedia.org/wiki/Holat",
    "https://id.wikipedia.org/wiki/Toge_Panyabungan",
    "https://id.wikipedia.org/wiki/Tari_Gubang",
    "https://id.wikipedia.org/wiki/Babae",
    "https://id.wikipedia.org/wiki/Tari_dulang",
    "https://id.wikipedia.org/wiki/Sinandong_asahan",
    "https://id.wikipedia.org/wiki/Gendang_guro-guro_aron",
    "https://id.wikipedia.org/wiki/Pelleng",
    "https://id.wikipedia.org/wiki/Gotong",
    "https://id.wikipedia.org/wiki/Itak_Poul_Poul",
    "https://id.wikipedia.org/wiki/Kala_Bubu",
    "https://id.wikipedia.org/wiki/Mangarontas",
    "https://id.wikipedia.org/wiki/Tari_Tortor_Sombah",
    "https://id.wikipedia.org/wiki/Maena",
    "https://id.wikipedia.org/wiki/Hombo_Batu",
    "https://id.wikipedia.org/wiki/Tari_Moyo",
    "https://id.wikipedia.org/wiki/Hoho"
}

sumatera_barat_urls = {
    "https://id.wikipedia.org/wiki/Randang",
    "https://id.wikipedia.org/wiki/Rumah_Gadang",
    "https://id.wikipedia.org/wiki/Sistem_Garis_Keturunan_Ibu_di_Masyarakat_Minangkabau",
    "https://id.wikipedia.org/wiki/Kaba_Cindua_Mato",
    "https://id.wikipedia.org/wiki/Tari_Toga",
    "https://id.wikipedia.org/wiki/Songket_Pandai_Sikek",
    "https://id.wikipedia.org/wiki/Rongeng_Pasaman",
    "https://id.wikipedia.org/wiki/Indang_Piaman",
    "https://id.wikipedia.org/wiki/Tato_Mentawai",
    "https://id.wikipedia.org/wiki/Silek_Minang",
    "https://id.wikipedia.org/wiki/Ulu_Ambek",
    "https://id.wikipedia.org/wiki/Rabab",
    "https://id.wikipedia.org/wiki/Salawat_Dulang",
    "https://id.wikipedia.org/wiki/Pasambahan",
    "https://id.wikipedia.org/wiki/Batombe",
    "https://id.wikipedia.org/wiki/Tari_Tanduak",
    "https://id.wikipedia.org/wiki/Tari_Piriang_(Tari_Piring)",
    "https://id.wikipedia.org/wiki/Randai",
    "https://id.wikipedia.org/wiki/Bahasa_Tansi_Sawahlunto",
    "https://id.wikipedia.org/wiki/Babiola",
    "https://id.wikipedia.org/wiki/Talempong_Unggan",
    "https://id.wikipedia.org/wiki/Tari_Benten",
    "https://id.wikipedia.org/wiki/Sikerei",
    "https://id.wikipedia.org/wiki/Botatah",
    "https://id.wikipedia.org/wiki/Arak_Bako",
    "https://id.wikipedia.org/wiki/Songket_Silungkang",
    "https://id.wikipedia.org/wiki/Sikambang_Manih",
    "https://id.wikipedia.org/wiki/Tari_kain",
    "https://id.wikipedia.org/wiki/Anak_Balam",
    "https://id.wikipedia.org/wiki/Diki_Pano",
    "https://id.wikipedia.org/wiki/Balimau",
    "https://id.wikipedia.org/wiki/Badampiang",
    "https://id.wikipedia.org/wiki/Basapa",
    "https://id.wikipedia.org/wiki/Marosok",
    "https://id.wikipedia.org/wiki/Uma",
    "https://id.wikipedia.org/wiki/Tari_Balanse_Madam",
    "https://id.wikipedia.org/wiki/Pacu_Jawi",
    "https://id.wikipedia.org/wiki/Pacu_itiak",
    "https://id.wikipedia.org/wiki/Gamad",
    "https://id.wikipedia.org/wiki/Randang_paku",
    "https://id.wikipedia.org/wiki/Bansi",
    "https://id.wikipedia.org/wiki/Tambua_Tasa",
    "https://id.wikipedia.org/wiki/Saluang",
    "https://id.wikipedia.org/wiki/Dadih",
    "https://id.wikipedia.org/wiki/Makan_bajamba",
    "https://id.wikipedia.org/wiki/Batik_Tanah_Liat",
    "https://id.wikipedia.org/wiki/Malamang",
    "https://id.wikipedia.org/wiki/Teh_talua",
    "https://id.wikipedia.org/wiki/Aia_kawa",
    "https://id.wikipedia.org/wiki/Sijobang",
    "https://id.wikipedia.org/wiki/Rumah_Gadang_Kajang_Padati",
    "https://id.wikipedia.org/wiki/Badoncek",
    "https://id.wikipedia.org/wiki/Serak_Gulo"
}

riau_place_urls = {
    "https://id.wikipedia.org/wiki/Tenun_Siak",
    "https://id.wikipedia.org/wiki/Koba",
    "https://id.wikipedia.org/wiki/Pacu_Jalur",
    "https://id.wikipedia.org/wiki/Menumbai_Pelalawan",
    "https://id.wikipedia.org/wiki/Randai_Kuantan",
    "https://id.wikipedia.org/wiki/Nyanyi_Panjang",
    "https://id.wikipedia.org/wiki/Bedewo_Bonai",
    "https://id.wikipedia.org/wiki/Debus_Indragiri_Hulu",
    "https://id.wikipedia.org/wiki/Calempong_Oguong",
    "https://id.wikipedia.org/wiki/Joget_Sonde",
    "https://id.wikipedia.org/wiki/Tunjuk_Ajar_Melayu",
    "https://id.wikipedia.org/wiki/Sijobang",
    "https://id.wikipedia.org/wiki/Silat_perisai",
    "https://id.wikipedia.org/wiki/Zapin_Api",
    "https://id.wikipedia.org/wiki/Zapin_Meskom",
    "https://id.wikipedia.org/wiki/Manongkah",
    "https://id.wikipedia.org/wiki/Perahu_Beganduang",
    "https://id.wikipedia.org/wiki/Batobo",
    "https://id.wikipedia.org/wiki/Rumah_Lontiok",
    "https://id.wikipedia.org/wiki/Selembayung_Riau",
    "https://id.wikipedia.org/wiki/Onduo_Rokan",
    "https://id.wikipedia.org/wiki/Silek_Tigo_Bulan",
    "https://id.wikipedia.org/wiki/Syair_Siak_Sri_Indrapura",
    "https://id.wikipedia.org/wiki/Ratik_Bosa/_Ratik_Tagak",
    "https://id.wikipedia.org/wiki/Ghatib_Beghanyut",
    "https://id.wikipedia.org/wiki/Lukah_Gilo_Riau",
    "https://id.wikipedia.org/wiki/Belian_Riau",
    "https://id.wikipedia.org/wiki/Silat_Pangean",
    "https://id.wikipedia.org/wiki/Kotik_Adat_Kampar",
    "https://id.wikipedia.org/wiki/Badondong",
    "https://id.wikipedia.org/wiki/Nandung_Indragiri_Hulu",
    "https://id.wikipedia.org/wiki/Kayat_Kuansing/Kayat_Rantau_Kuantan",
    "https://id.wikipedia.org/wiki/Pantun_Atui",
    "https://id.wikipedia.org/wiki/Tari_Gendong",
    "https://id.wikipedia.org/wiki/Burung_Kwayang",
    "https://id.wikipedia.org/wiki/Tari_Cegak",
    "https://id.wikipedia.org/wiki/Tari_Zapin",
    "https://id.wikipedia.org/wiki/Syair_Surat_Kapal",
    "https://id.wikipedia.org/wiki/Tepuk_tepung_tawar",
    "https://id.wikipedia.org/wiki/Dikei_Sakai",
    "https://id.wikipedia.org/wiki/Tari_Inai_Piring_Dua_Belas",
    "https://id.wikipedia.org/wiki/Upah-upah"
}

kepulauan_riau_urls = {
    "https://id.wikipedia.org/wiki/Makyong",
    "https://id.wikipedia.org/wiki/Gurindam_Dua_Belas",
    "https://id.wikipedia.org/wiki/Gazal",
    "https://id.wikipedia.org/wiki/Pantun_Melayu",
    "https://id.wikipedia.org/wiki/Gendang_Siantan",
    "https://id.wikipedia.org/wiki/Tari_Gubang",
    "https://id.wikipedia.org/wiki/Teater_Bangsawan",
    "https://id.wikipedia.org/wiki/Joget_Dangkong",
    "https://id.wikipedia.org/wiki/Bejenjang",
    "https://id.wikipedia.org/wiki/Tari_Inai",
    "https://id.wikipedia.org/wiki/Tepuk_Tepung_Tawar_Kepulauan_Riau",
    "https://id.wikipedia.org/wiki/Bubur_Lambok_Lingga",
    "https://id.wikipedia.org/wiki/Mandi_Syafar_Kepulauan_Riau",
    "https://id.wikipedia.org/wiki/Ratib_Saman_Lingga",
    "https://id.wikipedia.org/wiki/Silat_Pengantin_Kepulauan_Riau",
    "https://id.wikipedia.org/wiki/Basuh_Lantai",
    "https://id.wikipedia.org/wiki/Bersih_Tembuni_Lingga",
    "https://id.wikipedia.org/wiki/Bela_Kampong",
    "https://id.wikipedia.org/wiki/Kue_bangkit",
    "https://id.wikipedia.org/wiki/Kue_batang_buruk"
}

jambi_urls = {
    "https://id.wikipedia.org/wiki/Krinok",
    "https://id.wikipedia.org/wiki/Aksara_Kaganga",
    "https://id.wikipedia.org/wiki/Aksara_Incung",
    "https://id.wikipedia.org/wiki/Seloko_Melayu_Jambi",
    "https://id.wikipedia.org/wiki/Hadrah",
    "https://id.wikipedia.org/wiki/Besale",
    "https://id.wikipedia.org/wiki/Upacara_Asyeik",
    "https://id.wikipedia.org/wiki/Tauh_(Betauh)",
    "https://id.wikipedia.org/wiki/Tari_Kain_Kromong",
    "https://id.wikipedia.org/wiki/Musik_Kalinong",
    "https://id.wikipedia.org/wiki/Tari_elang",
    "https://id.wikipedia.org/wiki/Tomboi_Sialong",
    "https://id.wikipedia.org/wiki/Tomboi_Ngambek_Rapa",
    "https://id.wikipedia.org/wiki/Sebelik_Sumpah",
    "https://id.wikipedia.org/wiki/Ambung_Orang_Rimbo",
    "https://id.wikipedia.org/wiki/Cawot",
    "https://id.wikipedia.org/wiki/Ubat_Ramuon_Orang_Rimbo",
    "https://id.wikipedia.org/wiki/Belangun_Orang_Rimbo",
    "https://id.wikipedia.org/wiki/Hompongon",
    "https://id.wikipedia.org/wiki/Musik_Gambang_Dano_Lamo",
    "https://id.wikipedia.org/wiki/Tari_kadam",
    "https://id.wikipedia.org/wiki/Rangguk_Kumun",
    "https://id.wikipedia.org/wiki/Lapaek_Koto_Dian_Rawang",
    "https://id.wikipedia.org/wiki/Kenduri_Sko",
    "https://id.wikipedia.org/wiki/Tauh_Lempur",
    "https://id.wikipedia.org/wiki/Ntak_Awo",
    "https://id.wikipedia.org/wiki/Ampek_Gonjie_Limo_Gonop",
    "https://id.wikipedia.org/wiki/Perkampungan_Tradisional_Rumah_Tuo_Rantau_Panjang",
    "https://id.wikipedia.org/wiki/Tari_Iyo-Iyo",
    "https://id.wikipedia.org/wiki/Ngagoah_Imo_Pulau_Tengah",
    "https://id.wikipedia.org/wiki/Tari_Ayam_Biring",
    "https://id.wikipedia.org/wiki/Dadung"
}

sumatera_selatan_urls = {
    "https://id.wikipedia.org/wiki/Dulmuluk",
    "https://id.wikipedia.org/wiki/Songket_Palembang",
    "https://id.wikipedia.org/wiki/Tari_Gending_Sriwijaya",
    "https://id.wikipedia.org/wiki/Tembang_Batanghari_Sembilan",
    "https://id.wikipedia.org/wiki/Pempek",
    "https://id.wikipedia.org/wiki/Rumah_Ulu",
    "https://id.wikipedia.org/wiki/Limas_Palembang",
    "https://id.wikipedia.org/wiki/Senjang",
    "https://id.wikipedia.org/wiki/Rumah_Besemah",
    "https://id.wikipedia.org/wiki/Lak",
    "https://id.wikipedia.org/wiki/Tari_penguton",
    "https://id.wikipedia.org/wiki/Adat_Timbang_Kepala_Kebo",
    "https://id.wikipedia.org/wiki/Ngobeng",
    "https://id.wikipedia.org/wiki/Tari_Kebagh",
    "https://id.wikipedia.org/wiki/Tari_Silampari_Kahyangan_Tinggi",
    "https://id.wikipedia.org/wiki/Pindang_Palembang",
    "https://id.wikipedia.org/wiki/Tikar_Purun_Pedamaran",
    "https://id.wikipedia.org/wiki/Surat_Ulu",
    "https://id.wikipedia.org/wiki/Midang",
    "https://id.wikipedia.org/wiki/Tanjak_Palembang",
    "https://id.wikipedia.org/wiki/Cak_Ingkling",
    "https://id.wikipedia.org/wiki/Sedekah_Serabi",
    "https://id.wikipedia.org/wiki/Sedekah_Rame",
    "https://id.wikipedia.org/wiki/Sagarurung",
    "https://id.wikipedia.org/wiki/Burgo"
}

lampung_urls = {
    "https://id.wikipedia.org/wiki/Tapis",
    "https://id.wikipedia.org/wiki/Tari_Melinting",
    "https://id.wikipedia.org/wiki/Gamolan_pekhing",
    "https://id.wikipedia.org/wiki/Tari_Sigeh_Penguten",
    "https://id.wikipedia.org/wiki/Gulai_Taboh",
    "https://id.wikipedia.org/wiki/Seruit",
    "https://id.wikipedia.org/wiki/Cakak_Pepadun",
    "https://id.wikipedia.org/wiki/Warahan_Lampung",
    "https://id.wikipedia.org/wiki/Kakiceran",
    "https://id.wikipedia.org/wiki/Maduaro",
    "https://id.wikipedia.org/wiki/Tari_Nyambai",
    "https://id.wikipedia.org/wiki/Bediom",
    "https://id.wikipedia.org/wiki/Tari_Bedayou_Tulang_Bawang",
    "https://id.wikipedia.org/wiki/Dadi",
    "https://id.wikipedia.org/wiki/Siger_Lampung",
    "https://id.wikipedia.org/wiki/Ketaro_Adat_Lappung",
    "https://id.wikipedia.org/wiki/Nyuncun_Pahakh",
    "https://id.wikipedia.org/wiki/Tari_Bedana_Lampung",
    "https://id.wikipedia.org/wiki/Sebambangan",
    "https://id.wikipedia.org/wiki/Nyubuk_Majeu",
    "https://id.wikipedia.org/wiki/Kias",
    "https://id.wikipedia.org/wiki/Tari_Kiamat",
    "https://id.wikipedia.org/wiki/Piil_Pesenggiri",
    "https://id.wikipedia.org/wiki/Badik_Lampung",
    "https://id.wikipedia.org/wiki/Mekhatin",
    "https://id.wikipedia.org/wiki/Adok",
    "https://id.wikipedia.org/wiki/Hahiwang"
}

bengkulu_urls = {
    "https://id.wikipedia.org/wiki/Kain_Besurek",
    "https://id.wikipedia.org/wiki/Kain_Lantung",
    "https://id.wikipedia.org/wiki/Uemak_Potong_Jang",
    "https://id.wikipedia.org/wiki/Bekejai_(Upacara_Perkawinan_Suku_Rejang)",
    "https://id.wikipedia.org/wiki/Tari_Kejai",
    "https://id.wikipedia.org/wiki/Tari_Gandai",
    "https://id.wikipedia.org/wiki/Guritan_Kaur_Bengkulu",
    "https://id.wikipedia.org/wiki/Ringit",
    "https://id.wikipedia.org/wiki/Serunai_Bengkulu",
    "https://id.wikipedia.org/wiki/Tadutan",
    "https://id.wikipedia.org/wiki/Melemang",
    "https://id.wikipedia.org/wiki/Dhol"
}

bangka_belitung_urls = {
    "https://id.wikipedia.org/wiki/Muang_Jong",
    "https://id.wikipedia.org/wiki/Perang_Ketupat",
    "https://id.wikipedia.org/wiki/Adu_Kerito_Surong",
    "https://id.wikipedia.org/wiki/Kain_Cual",
    "https://id.wikipedia.org/wiki/Upacara_Adat_Nujuh_Jerami",
    "https://id.wikipedia.org/wiki/Maras_Taun",
    "https://id.wikipedia.org/wiki/Sepen_penyok",
    "https://id.wikipedia.org/wiki/Pakaian_Pengantin_Paksian",
    "https://id.wikipedia.org/wiki/Gangan",
    "https://id.wikipedia.org/wiki/Antu_Bubu",
    "https://id.wikipedia.org/wiki/Serimbang",
    "https://id.wikipedia.org/wiki/Hadrah_Gendang_Empat_Belitong",
    "https://id.wikipedia.org/wiki/Emping_Beras",
    "https://id.wikipedia.org/wiki/Sepen_Buding"
}

gorontalo_urls = {
    "https://id.wikipedia.org/wiki/Molapi_saronde",
    "https://id.wikipedia.org/wiki/Tumbilotohe",
    "https://id.wikipedia.org/wiki/Karawo",
    "https://id.wikipedia.org/wiki/Polopalo",
    "https://id.wikipedia.org/wiki/Tanggomo",
    "https://id.wikipedia.org/wiki/Lohidu",
    "https://id.wikipedia.org/wiki/Langga",
    "https://id.wikipedia.org/wiki/Binte_Biluhuta",
    "https://id.wikipedia.org/wiki/Paiya_Lohungo_Lopoli",
    "https://id.wikipedia.org/wiki/Tuja%27i",
    "https://id.wikipedia.org/wiki/Wunungo",
    "https://id.wikipedia.org/wiki/Tidi_lo_Polopalo",
    "https://id.wikipedia.org/wiki/Palebohu",
    "https://id.wikipedia.org/wiki/Dikili",
    "https://id.wikipedia.org/wiki/Me%27eraji",
    "https://id.wikipedia.org/wiki/Pulanga",
    "https://id.wikipedia.org/wiki/Momeati",
    "https://id.wikipedia.org/wiki/Molalunga",
    "https://id.wikipedia.org/wiki/Momuhuto",
    "https://id.wikipedia.org/wiki/Tolobalango",
    "https://id.wikipedia.org/wiki/Bantayo_Poboide",
    "https://id.wikipedia.org/wiki/Upiya_Karanji",
    "https://id.wikipedia.org/wiki/Molontalo",
    "https://id.wikipedia.org/wiki/Ilabulo",
    "https://id.wikipedia.org/wiki/Leningo",
    "https://id.wikipedia.org/wiki/Bili%27u",
    "https://id.wikipedia.org/wiki/Wunungo",
    "https://id.wikipedia.org/wiki/Paluwala",
    "https://id.wikipedia.org/wiki/Wolimomo"
}

dki_jakarta_urls = {
    "https://id.wikipedia.org/wiki/Ondel-ondel",
    "https://id.wikipedia.org/wiki/Lenong",
    "https://id.wikipedia.org/wiki/Upacara_Babarit",
    "https://id.wikipedia.org/wiki/Nasi_Uduk",
    "https://id.wikipedia.org/wiki/Sayur_Besan",
    "https://id.wikipedia.org/wiki/Kerak_Telor",
    "https://id.wikipedia.org/wiki/Gabus_Pucung",
    "https://id.wikipedia.org/wiki/Roti_Buaya",
    "https://id.wikipedia.org/wiki/Bir_Pletok",
    "https://id.wikipedia.org/wiki/Tanjidor",
    "https://id.wikipedia.org/wiki/(Buka)_Palang_Pintu",
    "https://id.wikipedia.org/wiki/Gambang_Kromong",
    "https://id.wikipedia.org/wiki/Silat_Beksi",
    "https://id.wikipedia.org/wiki/Samrah",
    "https://id.wikipedia.org/wiki/Keroncong_Tugu",
    "https://id.wikipedia.org/wiki/Topeng_Blantek",
    "https://id.wikipedia.org/wiki/Soto_Betawi",
    "https://id.wikipedia.org/wiki/Gado-gado_Betawi",
    "https://id.wikipedia.org/wiki/Rias_Besar",
    "https://id.wikipedia.org/wiki/Kebaya_Kerancang",
    "https://id.wikipedia.org/wiki/Batik_Betawi",
    "https://id.wikipedia.org/wiki/Topeng_tunggal",
    "https://id.wikipedia.org/wiki/Penganten_Sunat",
    "https://id.wikipedia.org/wiki/Rebana_Biang",
    "https://id.wikipedia.org/wiki/Hadroh_Betawi",
    "https://id.wikipedia.org/wiki/Dodol_Betawi",
    "https://id.wikipedia.org/wiki/Silat_Cingkrik",
    "https://id.wikipedia.org/wiki/Bahasa_Betawi",
    "https://id.wikipedia.org/wiki/Caca_Gulali",
    "https://id.wikipedia.org/wiki/Cici_Putri",
    "https://id.wikipedia.org/wiki/Kembang_Kelape",
    "https://id.wikipedia.org/wiki/Uncul",
    "https://id.wikipedia.org/wiki/Nasi_Ulam_Betawi",
    "https://id.wikipedia.org/wiki/Wayang_Kulit_Betawi",
    "https://id.wikipedia.org/wiki/Silat_Mustika_Kwitang",
    "https://id.wikipedia.org/wiki/Ketupat_Sayur_Babanci",
    "https://id.wikipedia.org/wiki/Kue_Sengkulun",
    "https://id.wikipedia.org/wiki/Selendang_Mayang",
    "https://id.wikipedia.org/wiki/Silat_Sabeni_Tenabang",
    "https://id.wikipedia.org/wiki/Asinan_Betawi",
    "https://id.wikipedia.org/wiki/Dangdut"
}

jawa_barat_urls = {
    "https://id.wikipedia.org/wiki/Kujang",
    "https://id.wikipedia.org/wiki/Ronggeng_Gunung",
    "https://id.wikipedia.org/wiki/Sisingaan",
    "https://id.wikipedia.org/wiki/Angklung",
    "https://id.wikipedia.org/wiki/Tari_Topeng_Cirebon",
    "https://id.wikipedia.org/wiki/Kuda_Renggong",
    "https://id.wikipedia.org/wiki/Jaipong",
    "https://id.wikipedia.org/wiki/Sintren",
    "https://id.wikipedia.org/wiki/Ngarot",
    "https://id.wikipedia.org/wiki/Ngalungsur_Geni_(Ngalungsur_Pusaka)",
    "https://id.wikipedia.org/wiki/Lais_Garut",
    "https://id.wikipedia.org/wiki/Lukis_kaca_Cirebon",
    "https://id.wikipedia.org/wiki/Gembyung",
    "https://id.wikipedia.org/wiki/Iket_Sunda",
    "https://id.wikipedia.org/wiki/Kolecer_Jawa_Barat",
    "https://id.wikipedia.org/wiki/Leuit",
    "https://id.wikipedia.org/wiki/Nyangku",
    "https://id.wikipedia.org/wiki/Angklung_Buncis",
    "https://id.wikipedia.org/wiki/Badud",
    "https://id.wikipedia.org/wiki/Bebegig",
    "https://id.wikipedia.org/wiki/Gaok",
    "https://id.wikipedia.org/wiki/Gondang_Buhun",
    "https://id.wikipedia.org/wiki/Hajat_Laut",
    "https://id.wikipedia.org/wiki/Kuda_Kosong",
    "https://id.wikipedia.org/wiki/Ngabungbang_Batulawang",
    "https://id.wikipedia.org/wiki/Ngalaksa",
    "https://id.wikipedia.org/wiki/Reog_Dongkol",
    "https://id.wikipedia.org/wiki/Sate_Maranggi",
    "https://id.wikipedia.org/wiki/Tarawangsa",
    "https://id.wikipedia.org/wiki/Tari_Kedempling",
    "https://id.wikipedia.org/wiki/Tari_Umbul",
    "https://id.wikipedia.org/wiki/Tarling",
    "https://id.wikipedia.org/wiki/Uyeg",
    "https://id.wikipedia.org/wiki/Badawang",
    "https://id.wikipedia.org/wiki/Benjang_(beladiri)",
    "https://id.wikipedia.org/wiki/Cingcowong",
    "https://id.wikipedia.org/wiki/Domyak",
    "https://id.wikipedia.org/wiki/Kawin_Cai",
    "https://id.wikipedia.org/wiki/Upacara_panjang_jimat",
    "https://id.wikipedia.org/wiki/Tari_Randu_Kentir",
    "https://id.wikipedia.org/wiki/Topeng_Banjet",
    "https://id.wikipedia.org/wiki/Tari_Merak",
    "https://id.wikipedia.org/wiki/Angklung_Bungko",
    "https://id.wikipedia.org/wiki/Gong_Si_Bolong",
    "https://id.wikipedia.org/wiki/Toleat",
    "https://id.wikipedia.org/wiki/Payung_geulis",
    "https://id.wikipedia.org/wiki/Jipeng",
    "https://id.wikipedia.org/wiki/Karinding",
    "https://id.wikipedia.org/wiki/Doclang",
    "https://id.wikipedia.org/wiki/Degung",
    "https://id.wikipedia.org/wiki/Gong_Renteng_Cirebon",
    "https://id.wikipedia.org/wiki/Tari_Ketuk_Tilu",
    "https://id.wikipedia.org/wiki/Bedaya_Rimbe",
    "https://id.wikipedia.org/wiki/Celempung",
    "https://id.wikipedia.org/wiki/Kiliningan",
    "https://id.wikipedia.org/wiki/Longser",
    "https://id.wikipedia.org/wiki/Arumba",
    "https://id.wikipedia.org/wiki/Krupuk_Mlarat",
    "https://id.wikipedia.org/wiki/Sega_Jamblang",
    "https://id.wikipedia.org/wiki/Wajit"
}

banten_urls = {
    "https://id.wikipedia.org/wiki/Debus_Banten",
    "https://id.wikipedia.org/wiki/Tari_Cokek",
    "https://id.wikipedia.org/wiki/Sate_bandeng",
    "https://id.wikipedia.org/wiki/Seren_taun",
    "https://id.wikipedia.org/wiki/Golok_Sulangkar",
    "https://id.wikipedia.org/wiki/Golok_Ciomas",
    "https://id.wikipedia.org/wiki/Zikir_Saman",
    "https://id.wikipedia.org/wiki/Patingtung",
    "https://id.wikipedia.org/wiki/Wayang_Garing",
    "https://id.wikipedia.org/wiki/Tari_Rudat_Banten",
    "https://id.wikipedia.org/wiki/Koja",
    "https://id.wikipedia.org/wiki/Maca_Syekh",
    "https://id.wikipedia.org/wiki/Gambang_Kromong"
}

jawa_tengah_urls = {
    "https://id.wikipedia.org/wiki/Keris",
    "https://id.wikipedia.org/wiki/Lumpia_Semarang",
    "https://id.wikipedia.org/wiki/Ukir_Jepara",
    "https://id.wikipedia.org/wiki/Upacara_Adat_Apeman_Yaqowiyu",
    "https://id.wikipedia.org/wiki/Ruwatan_Rambut_Gimbal",
    "https://id.wikipedia.org/wiki/Meron",
    "https://id.wikipedia.org/wiki/Tari_Gambyong",
    "https://id.wikipedia.org/wiki/Joglo_Pencu_(Rumah_Adat_Kudus)",
    "https://id.wikipedia.org/wiki/Tempe_Jawa_Tengah",
    "https://id.wikipedia.org/wiki/Barongan_Blora",
    "https://id.wikipedia.org/wiki/Gethuk_Goreng_Sokaraja",
    "https://id.wikipedia.org/wiki/Manten_Kaji",
    "https://id.wikipedia.org/wiki/Tari_Endel",
    "https://id.wikipedia.org/wiki/Grebeg_Besar_Demak",
    "https://id.wikipedia.org/wiki/Hak-Hakan",
    "https://id.wikipedia.org/wiki/Gambang_Semarang",
    "https://id.wikipedia.org/wiki/Begalan_Banyumas",
    "https://id.wikipedia.org/wiki/Kethek_Ogleng_Wonogiri",
    "https://id.wikipedia.org/wiki/Sedulur_Sikep_Blora",
    "https://id.wikipedia.org/wiki/Dolalak",
    "https://id.wikipedia.org/wiki/Sintren",
    "https://id.wikipedia.org/wiki/Jamu",
    "https://id.wikipedia.org/wiki/Dakon_Jawa_Tengah",
    "https://id.wikipedia.org/wiki/Dugderan",
    "https://id.wikipedia.org/wiki/Wayang_suket",
    "https://id.wikipedia.org/wiki/Perang_Obor_Tegalsambi",
    "https://id.wikipedia.org/wiki/Jembul_Tulakan",
    "https://id.wikipedia.org/wiki/Telur_Asin_Brebes",
    "https://id.wikipedia.org/wiki/Pesta_Lomban",
    "https://id.wikipedia.org/wiki/Tari_Topeng_Lengger",
    "https://id.wikipedia.org/wiki/Bundengan",
    "https://id.wikipedia.org/wiki/Sate_Kere",
    "https://id.wikipedia.org/wiki/Seni_pertunjukan",
    "https://id.wikipedia.org/wiki/Sate_Buntel",
    "https://id.wikipedia.org/wiki/Ngesti_Pandowo",
    "https://id.wikipedia.org/wiki/Warak_ngendog",
    "https://id.wikipedia.org/wiki/Barongan_Kudus",
    "https://id.wikipedia.org/wiki/Jenang_Kudus",
    "https://id.wikipedia.org/wiki/Tempe_kemul",
    "https://id.wikipedia.org/wiki/Batik_Salem",
    "https://id.wikipedia.org/wiki/Potehi"
}

yogyakarta_urls = {
    "https://id.wikipedia.org/wiki/Joglo",
    "https://id.wikipedia.org/wiki/Gudeg",
    "https://id.wikipedia.org/wiki/Saparan",
    "https://id.wikipedia.org/wiki/Labuhan_Alit_Keraton_Yogyakarta",
    "https://id.wikipedia.org/wiki/Tari_Angguk",
    "https://id.wikipedia.org/wiki/Badui",
    "https://id.wikipedia.org/wiki/Khuntulan",
    "https://id.wikipedia.org/wiki/Montro",
    "https://id.wikipedia.org/wiki/Rinding_Gumbeng",
    "https://id.wikipedia.org/wiki/Srandul",
    "https://id.wikipedia.org/wiki/Panjidur",
    "https://id.wikipedia.org/wiki/Tari_Golek_Menak",
    "https://id.wikipedia.org/wiki/Srimpi_Ronggo_Janur",
    "https://id.wikipedia.org/wiki/Dadung_Awuk",
    "https://id.wikipedia.org/wiki/Krumpyung_Kulon_Progo",
    "https://id.wikipedia.org/wiki/Wedang_uwuh",
    "https://id.wikipedia.org/wiki/Wayang_Beber_Remeng_Mangunjoyo",
    "https://id.wikipedia.org/wiki/Wayang_wong_gaya_yogyakarta",
    "https://id.wikipedia.org/wiki/Wayang_Kancil_Yogyakarta",
    "https://id.wikipedia.org/wiki/Beksan_Jebeng",
    "https://id.wikipedia.org/wiki/Beksan_Floret",
    "https://id.wikipedia.org/wiki/Bedhaya_Tejanata_Pakualaman",
    "https://id.wikipedia.org/wiki/Bedhaya_Kuwung-Kuwung",
    "https://id.wikipedia.org/wiki/Beksan_Guntur_Segara",
    "https://id.wikipedia.org/wiki/Beksan_Bugis_Gaya_Yogyakarta",
    "https://id.wikipedia.org/wiki/Kethek_ogleng",
    "https://id.wikipedia.org/wiki/Gejog_Lesung_Yogyakarta",
    "https://id.wikipedia.org/wiki/Macapatan_Yogyakarta",
    "https://id.wikipedia.org/wiki/Benthik_Yogyakarta",
    "https://id.wikipedia.org/wiki/Peksi_Moi",
    "https://id.wikipedia.org/wiki/Saparan_Wonolelo",
    "https://id.wikipedia.org/wiki/Rabu_pungkasan",
    "https://id.wikipedia.org/wiki/Geplak",
    "https://id.wikipedia.org/wiki/Geblek",
    "https://id.wikipedia.org/wiki/Dandan_Kali",
    "https://id.wikipedia.org/wiki/Tayub_Yogyakarta",
    "https://id.wikipedia.org/wiki/Brongkos_Yogyakarta",
    "https://id.wikipedia.org/wiki/Beksan_Etheng",
    "https://id.wikipedia.org/wiki/Golek_Lambangsari_Yogyakarta",
    "https://id.wikipedia.org/wiki/Batik_Nitik_Yogyakarta",
    "https://id.wikipedia.org/wiki/Beksan_Golek_Pucung_Kethoprak",
    "https://id.wikipedia.org/wiki/Nini_Thowong_Yogyakarta",
    "https://id.wikipedia.org/wiki/Sate_klatak",
    "https://id.wikipedia.org/wiki/Mi_letheg",
    "https://id.wikipedia.org/wiki/Kipo",
    "https://id.wikipedia.org/wiki/Growol",
    "https://id.wikipedia.org/wiki/Kampung_Pitu",
    "https://id.wikipedia.org/wiki/Nguras_Enceh",
    "https://id.wikipedia.org/wiki/Besengek",
    "https://id.wikipedia.org/wiki/Rasulan",
    "https://id.wikipedia.org/wiki/Reog_Wayang",
    "https://id.wikipedia.org/wiki/Upacara_adat_Mbah_Bregas",
    "https://id.wikipedia.org/wiki/Tuk_si_bedug",
    "https://id.wikipedia.org/wiki/Jemparingan",
    "https://id.wikipedia.org/wiki/Thiwul",
    "https://id.wikipedia.org/wiki/Lemper",
    "https://id.wikipedia.org/wiki/Gudeg_Manggar",
    "https://id.wikipedia.org/wiki/Gobak_sodor",
    "https://id.wikipedia.org/wiki/Sayur_lodeh",
    "https://id.wikipedia.org/wiki/Jadah_manten",
    "https://id.wikipedia.org/wiki/Jamu",
    "https://id.wikipedia.org/wiki/Yangko",
    "https://id.wikipedia.org/wiki/Aksara_Jawa"
}

jawa_timur_urls = {
    "https://id.wikipedia.org/wiki/Reog_Ponorogo",
    "https://id.wikipedia.org/wiki/Keraben_Sape_(Karapan_Sapi)",
    "https://id.wikipedia.org/wiki/Sapi_Sonok",
    "https://id.wikipedia.org/wiki/Gandrung_Banyuwangi",
    "https://id.wikipedia.org/wiki/Kentrung",
    "https://id.wikipedia.org/wiki/Tari_Seblang",
    "https://id.wikipedia.org/wiki/Wayang_Topeng",
    "https://id.wikipedia.org/wiki/Tumpeng_Sewu",
    "https://id.wikipedia.org/wiki/Syiir_Madura",
    "https://id.wikipedia.org/wiki/Kasada",
    "https://id.wikipedia.org/wiki/Ludruk",
    "https://id.wikipedia.org/wiki/Jaran_Bodhag",
    "https://id.wikipedia.org/wiki/Dongkrek",
    "https://id.wikipedia.org/wiki/Larung_Sembonyo",
    "https://id.wikipedia.org/wiki/Singo_Ulung",
    "https://id.wikipedia.org/wiki/Wayang_Beber",
    "https://id.wikipedia.org/wiki/Tanean_lanjang",
    "https://id.wikipedia.org/wiki/Jaran_Kencak",
    "https://id.wikipedia.org/wiki/Wayang_krucil",
    "https://id.wikipedia.org/wiki/Ayam_lodho",
    "https://id.wikipedia.org/wiki/Sandhur_Manduro",
    "https://id.wikipedia.org/wiki/Nyadar_(upacara_adat)",
    "https://id.wikipedia.org/wiki/Ceprotan",
    "https://id.wikipedia.org/wiki/Jamasan_Gong_Kiai_Pradah",
    "https://id.wikipedia.org/wiki/Damar_Kurung",
    "https://id.wikipedia.org/wiki/Celurit",
    "https://id.wikipedia.org/wiki/Janger_Banyuwangi",
    "https://id.wikipedia.org/wiki/Manten_kucing",
    "https://id.wikipedia.org/wiki/Rawon_Nguling_Probolinggo",
    "https://id.wikipedia.org/wiki/Reog_Cemandi",
    "https://id.wikipedia.org/wiki/Sandur",
    "https://id.wikipedia.org/wiki/Wayang_Thengul",
    "https://id.wikipedia.org/wiki/Topeng_jatiduwur",
    "https://id.wikipedia.org/wiki/Bantengan",
    "https://id.wikipedia.org/wiki/Ojhung",
    "https://id.wikipedia.org/wiki/Saronen",
    "https://id.wikipedia.org/wiki/Tetaken",
    "https://id.wikipedia.org/wiki/Rujak_cingur",
    "https://id.wikipedia.org/wiki/Nasi_krawu",
    "https://id.wikipedia.org/wiki/Wayang_krucil",
    "https://id.wikipedia.org/wiki/Pecel_Madiun",
    "https://id.wikipedia.org/wiki/Jaranan_Pegon",
    "https://id.wikipedia.org/wiki/Jaran_Jenggo",
    "https://id.wikipedia.org/wiki/Tari_Ngremo",
    "https://id.wikipedia.org/wiki/Brem"
}

bali_urls = {
    "https://id.wikipedia.org/wiki/Mekepung",
    "https://id.wikipedia.org/wiki/Kain_gringsing",
    "https://id.wikipedia.org/wiki/Endek",
    "https://id.wikipedia.org/wiki/Barong_Bali#Barong_Ket_atau_Barong_Keket",
    "https://id.wikipedia.org/wiki/Joged",
    "https://id.wikipedia.org/wiki/Legong",
    "https://id.wikipedia.org/wiki/Wayang_orang",
    "https://id.wikipedia.org/wiki/Gambuh",
    "https://id.wikipedia.org/wiki/Topeng_Sidakarya",
    "https://id.wikipedia.org/wiki/Tari_Sanghyang",
    "https://id.wikipedia.org/wiki/Tari_Rejang",
    "https://id.wikipedia.org/wiki/Mekotek",
    "https://id.wikipedia.org/wiki/Ter-teran",
    "https://id.wikipedia.org/wiki/Gebug_ende",
    "https://id.wikipedia.org/wiki/Ayam_betutu",
    "https://id.wikipedia.org/wiki/Gamelan_Selonding",
    "https://id.wikipedia.org/wiki/Usaba_Dangsil",
    "https://id.wikipedia.org/wiki/Usaba_Sumbu",
    "https://id.wikipedia.org/wiki/Siat_tipat_bantal",
    "https://id.wikipedia.org/wiki/Leko",
    "https://id.wikipedia.org/wiki/Siat_Geni",
    "https://id.wikipedia.org/wiki/Jegog",
    "https://id.wikipedia.org/wiki/Terompong_beru",
    "https://id.wikipedia.org/wiki/Megibung",
    "https://id.wikipedia.org/wiki/Mesabat-Sabatan_Biu",
    "https://id.wikipedia.org/wiki/Songket_Beratan",
    "https://id.wikipedia.org/wiki/Tari_baris_wayang",
    "https://id.wikipedia.org/wiki/Tari_baris_cina",
    "https://id.wikipedia.org/wiki/Basmerah",
    "https://id.wikipedia.org/wiki/Ngarebong_Kesiman",
    "https://id.wikipedia.org/wiki/Tari_Taruna_Jaya",
    "https://id.wikipedia.org/wiki/Nyakan_Diwang",
    "https://id.wikipedia.org/wiki/Sate_Renteng",
    "https://id.wikipedia.org/wiki/Mandolin",
    "https://id.wikipedia.org/wiki/Babi_guling",
    "https://id.wikipedia.org/wiki/Sate_Lilit",
    "https://id.wikipedia.org/wiki/Ngaben",
    "https://id.wikipedia.org/wiki/Melukat",
    "https://id.wikipedia.org/wiki/Nyepi"
}

nusa_tenggara_barat_urls = {
    "https://id.wikipedia.org/wiki/Gendang_Beleq",
    "https://id.wikipedia.org/wiki/Perisean",
    "https://id.wikipedia.org/wiki/Ayam_Taliwang",
    "https://id.wikipedia.org/wiki/Pacoa_Jara,_Pacu_Mbojo",
    "https://id.wikipedia.org/wiki/Kareku_Kandei",
    "https://id.wikipedia.org/wiki/Bau_Nyale",
    "https://id.wikipedia.org/wiki/Tenun_Pringgasela"
}

nusa_tenggara_timur_urls = {
    "https://id.wikipedia.org/wiki/Sasandu_(Sasando)",
    "https://id.wikipedia.org/wiki/Caci",
    "https://id.wikipedia.org/wiki/Rumah_Bale_(Arsitektur_Sumba)",
    "https://id.wikipedia.org/wiki/Tenun_Ikat_Sumba",
    "https://id.wikipedia.org/wiki/Lodok",
    "https://id.wikipedia.org/wiki/Penti_Weki_Peso_Beo_Reca_Rangga_Wali_Ntaung",
    "https://id.wikipedia.org/wiki/Mbaru_Niang_Wae_Rebo",
    "https://id.wikipedia.org/wiki/Pasola",
    "https://id.wikipedia.org/wiki/Etu",
    "https://id.wikipedia.org/wiki/Repit",
    "https://id.wikipedia.org/wiki/Kure",
    "https://id.wikipedia.org/wiki/Wulla_Poddu",
    "https://id.wikipedia.org/wiki/Leru_Weru",
    "https://id.wikipedia.org/wiki/Matekio",
    "https://id.wikipedia.org/wiki/Tari_Likurai",
    "https://id.wikipedia.org/wiki/Se%27i",
    "https://id.wikipedia.org/wiki/Leva_nuang",
    "https://id.wikipedia.org/wiki/Ela_Ma",
    "https://id.wikipedia.org/wiki/Hole_(adat_istiadat)",
    "https://id.wikipedia.org/wiki/Vera",
    "https://id.wikipedia.org/wiki/Ti%27i_langga",
    "https://id.wikipedia.org/wiki/Ja%27i"
}

kalimantan_barat_urls = {
    "https://id.wikipedia.org/wiki/Festival_meriam_karbit",
    "https://id.wikipedia.org/wiki/Robo-robo",
    "https://id.wikipedia.org/wiki/Nyangahatn",
    "https://id.wikipedia.org/wiki/Jonggan",
    "https://id.wikipedia.org/wiki/Sape_Kalimantan_Barat",
    "https://id.wikipedia.org/wiki/Tumpang_Negeri",
    "https://id.wikipedia.org/wiki/Gawai_Dayak_Kalimantan_Barat",
    "https://id.wikipedia.org/wiki/Tenun_Corak_Insang",
    "https://id.wikipedia.org/wiki/Panganten_Dayak_Kanayatn",
    "https://id.wikipedia.org/wiki/Faradje%27",
    "https://id.wikipedia.org/wiki/Sayo%27_Keladi_Pontianak",
    "https://id.wikipedia.org/wiki/Pacri_Nenas_Pontianak",
    "https://id.wikipedia.org/wiki/Temet",
    "https://id.wikipedia.org/wiki/Bahasa_Melayu_Pontianak",
    "https://id.wikipedia.org/wiki/Bahasa_Melayu_Sambas"
}

kalimantan_selatan_urls = {
    "https://id.wikipedia.org/wiki/Sasirangan",
    "https://id.wikipedia.org/wiki/Madihin",
    "https://id.wikipedia.org/wiki/Aruh_Baharin",
    "https://id.wikipedia.org/wiki/Pasar_Terapung",
    "https://id.wikipedia.org/wiki/Lamut",
    "https://id.wikipedia.org/wiki/Kuriding/_Guriding",
    "https://id.wikipedia.org/wiki/Bubungan_Tinggi",
    "https://id.wikipedia.org/wiki/Ba%27ayun_Mulud/Maulid",
    "https://id.wikipedia.org/wiki/Batatamba",
    "https://id.wikipedia.org/wiki/Mamanda",
    "https://id.wikipedia.org/wiki/Tari_Baksa_Kembang",
    "https://id.wikipedia.org/wiki/Wayang_Kulit_Banjar",
    "https://id.wikipedia.org/wiki/Air_Guci",
    "https://id.wikipedia.org/wiki/Kuda_gipang",
    "https://id.wikipedia.org/wiki/Sinoman_Hadrah",
    "https://id.wikipedia.org/wiki/Wayang_Gung",
    "https://id.wikipedia.org/wiki/Balogo",
    "https://id.wikipedia.org/wiki/Mappanretasi_Pagatan",
    "https://id.wikipedia.org/wiki/Tenun_Pagatan",
    "https://id.wikipedia.org/wiki/Damarulan/Damarwulan_Banjarmasin",
    "https://id.wikipedia.org/wiki/Nasi_Astakona",
    "https://id.wikipedia.org/wiki/Rumah_Lanting",
    "https://id.wikipedia.org/wiki/Kurung-kurung",
    "https://id.wikipedia.org/wiki/Aruh_Bawanang",
    "https://id.wikipedia.org/wiki/Batatamba",
    "https://id.wikipedia.org/wiki/Tari_Banjar",
    "https://id.wikipedia.org/wiki/Tari_Radap_Rahayu",
    "https://id.wikipedia.org/wiki/Ladon",
    "https://id.wikipedia.org/wiki/Mesiwah_Pare_Gumboh",
    "https://id.wikipedia.org/wiki/Bapandung",
    "https://id.wikipedia.org/wiki/Arangan"
}

kalimantan_tengah_urls = {
    "https://id.wikipedia.org/wiki/Tiwah",
    "https://id.wikipedia.org/wiki/Sapundu",
    "https://id.wikipedia.org/wiki/Mamapus_Lewu",
    "https://id.wikipedia.org/wiki/Nahunan",
    "https://id.wikipedia.org/wiki/Wedian_dadas"
}

kalimantan_timur_urls = {
    "https://id.wikipedia.org/wiki/Tenun_Ulap_Doyo",
    "https://id.wikipedia.org/wiki/Belian_Bawo",
    "https://id.wikipedia.org/wiki/Hudoq",
    "https://id.wikipedia.org/wiki/Kwangkey",
    "https://id.wikipedia.org/wiki/Lom_Plai",
    "https://id.wikipedia.org/wiki/Mandau",
    "https://id.wikipedia.org/wiki/Blontang",
    "https://id.wikipedia.org/wiki/Erau",
    "https://id.wikipedia.org/wiki/Sarung_Samarinda",
    "https://id.wikipedia.org/wiki/Ganjur",
    "https://id.wikipedia.org/wiki/Tari_Gong",
    "https://id.wikipedia.org/wiki/Jatung_Utang"
}

kalimantan_utara_urls = {
    "https://id.wikipedia.org/wiki/Bening_dayak",
    "https://id.wikipedia.org/wiki/Jatung_Utang",
    "https://id.wikipedia.org/wiki/Tari_Magunatip",
    "https://id.wikipedia.org/wiki/Penurunan_Padaw_Tuju_Dulung",
    "https://id.wikipedia.org/wiki/Bebelen",
    "https://id.wikipedia.org/wiki/Melah_dan_Lakin_Ngayau",
    "https://id.wikipedia.org/wiki/Inter_Kesuma",
    "https://id.wikipedia.org/wiki/Bedibai"
}

sulawesi_selatan_urls = {
    "https://id.wikipedia.org/wiki/Pinisi",
    "https://id.wikipedia.org/wiki/Pa%27gellu",
    "https://id.wikipedia.org/wiki/Sinriliq",
    "https://id.wikipedia.org/wiki/Tari_Pakarena",
    "https://id.wikipedia.org/wiki/Tongkonan",
    "https://id.wikipedia.org/wiki/Badik",
    "https://id.wikipedia.org/wiki/Ma%27badong",
    "https://id.wikipedia.org/wiki/Coto_Makassar",
    "https://id.wikipedia.org/wiki/Aqraga",
    "https://id.wikipedia.org/wiki/Mappadendang",
    "https://id.wikipedia.org/wiki/Tudang_Sipulung",
    "https://id.wikipedia.org/wiki/Maudu_Lompoa",
    "https://id.wikipedia.org/wiki/Lipa%27_Sabbe",
    "https://id.wikipedia.org/wiki/Maccera_manurung",
    "https://id.wikipedia.org/wiki/Tari_Salonreng",
    "https://id.wikipedia.org/wiki/Barongko",
    "https://id.wikipedia.org/wiki/Balla_To_Kajang",
    "https://id.wikipedia.org/wiki/Kelong_Pakkiyo_Bunting",
    "https://id.wikipedia.org/wiki/Passura%27",
    "https://id.wikipedia.org/wiki/Rumah_Adat_Karampuang",
    "https://id.wikipedia.org/wiki/Kapurung",
    "https://id.wikipedia.org/wiki/Pajjaga_Bone_Balla",
    "https://id.wikipedia.org/wiki/Kajangki",
    "https://id.wikipedia.org/wiki/Gambus_Ogi",
    "https://id.wikipedia.org/wiki/Songkabala_Accera_Kalompoang",
    "https://id.wikipedia.org/wiki/Parade_Pasukan_A%27jaga_Tubarani",
    "https://id.wikipedia.org/wiki/Sirawu%27_Sulo",
    "https://id.wikipedia.org/wiki/Mattopang_Arajang",
    "https://id.wikipedia.org/wiki/Rambu_Solo%27",
    "https://id.wikipedia.org/wiki/Annyorong_lopi",
    "https://id.wikipedia.org/wiki/Mangrara_Banua",
    "https://id.wikipedia.org/wiki/Kelong_batti%27-batti%27",
    "https://id.wikipedia.org/wiki/Maccera_arajang",
    "https://id.wikipedia.org/wiki/Mappacci",
    "https://id.wikipedia.org/wiki/Passureq",
    "https://id.wikipedia.org/wiki/Mallangi_Arajang_Ri_Goarie",
    "https://id.wikipedia.org/wiki/Macceratasi",
    "https://id.wikipedia.org/wiki/Didek",
    "https://id.wikipedia.org/wiki/Tari_Moriringgo"
}

sulawesi_utara_urls = {
    "https://id.wikipedia.org/wiki/Tari_Maengket",
    "https://id.wikipedia.org/wiki/Mane%27e",
    "https://id.wikipedia.org/wiki/Kolintang",
    "https://id.wikipedia.org/wiki/Tulude",
    "https://id.wikipedia.org/wiki/Tari_kabela",
    "https://id.wikipedia.org/wiki/Masamper",
    "https://id.wikipedia.org/wiki/Tinutuan",
    "https://id.wikipedia.org/wiki/Figura",
    "https://id.wikipedia.org/wiki/Cakalang_fufu",
    "https://id.wikipedia.org/wiki/Mapalus"
}

sulawesi_tenggara_urls = {
    "https://id.wikipedia.org/wiki/Kalo_Sara",
    "https://id.wikipedia.org/wiki/Kabanti",
    "https://id.wikipedia.org/wiki/Lariangi",
    "https://id.wikipedia.org/wiki/Kaghati",
    "https://id.wikipedia.org/wiki/Mosehe",
    "https://id.wikipedia.org/wiki/Tari_Malulo",
    "https://id.wikipedia.org/wiki/Karia",
    "https://id.wikipedia.org/wiki/Tari_Linda",
    "https://id.wikipedia.org/wiki/Kantola",
    "https://id.wikipedia.org/wiki/Istana_Malige",
    "https://id.wikipedia.org/wiki/Kaago-Ago",
    "https://id.wikipedia.org/wiki/Pakande-Kandea",
    "https://id.wikipedia.org/wiki/Tari_Lumense",
    "https://id.wikipedia.org/wiki/Tari_Mondotambe",
    "https://id.wikipedia.org/wiki/Kabuenga"
}

sulawesi_tengah_urls = {
    "https://id.wikipedia.org/wiki/Raigo",
    "https://id.wikipedia.org/wiki/Sarung_Donggala",
    "https://id.wikipedia.org/wiki/Malabot_tumpe",
    "https://id.wikipedia.org/wiki/Padungku",
    "https://id.wikipedia.org/wiki/Kaledo",
    "https://id.wikipedia.org/wiki/Kakula",
    "https://id.wikipedia.org/wiki/Modulu-Dulu",
    "https://id.wikipedia.org/wiki/Balia",
    "https://id.wikipedia.org/wiki/Tari_Torompio",
    "https://id.wikipedia.org/wiki/Modero",
    "https://id.wikipedia.org/wiki/Rumah_Tambi"
}

sulawesi_barat_urls = {
    "https://id.wikipedia.org/wiki/Sayyang_pattudu",
    "https://id.wikipedia.org/wiki/Passayang-sayang",
    "https://id.wikipedia.org/wiki/Sandeq",
    "https://id.wikipedia.org/wiki/Calong",
    "https://id.wikipedia.org/wiki/Lipa_Saqbe_Mandar",
    "https://id.wikipedia.org/wiki/Mappatammaq_Al-Quran",
    "https://id.wikipedia.org/wiki/Maulidan_Salabose",
    "https://id.wikipedia.org/wiki/Pupu",
    "https://id.wikipedia.org/wiki/Kaliandaqdaq"
}

maluku_urls = {
    "https://id.wikipedia.org/wiki/Ehe_Lawn",
    "https://id.wikipedia.org/wiki/Tais_Pet",
    "https://id.wikipedia.org/wiki/Tari_Maku-Maku",
    "https://id.wikipedia.org/wiki/Rofaer_War_(Cuci_Parigi)",
    "https://id.wikipedia.org/wiki/Poya",
    "https://id.wikipedia.org/wiki/Pela",
    "https://id.wikipedia.org/wiki/Sasi",
    "https://id.wikipedia.org/wiki/Pukul_Manyapu",
    "https://id.wikipedia.org/wiki/Sopi",
    "https://id.wikipedia.org/wiki/Rumah_baileo",
    "https://id.wikipedia.org/wiki/Dansa_Tali",
    "https://id.wikipedia.org/wiki/Enbal",
    "https://id.wikipedia.org/wiki/Tahuri",
    "https://id.wikipedia.org/wiki/Pataheri/Matahena",
    "https://id.wikipedia.org/wiki/Gula_Saparua",
    "https://id.wikipedia.org/wiki/Tari_Lenso"
}

maluku_utara_urls = {
    "https://id.wikipedia.org/wiki/Bambu_Gila",
    "https://id.wikipedia.org/wiki/Soya-soya",
    "https://id.wikipedia.org/wiki/Hibualamo",
    "https://id.wikipedia.org/wiki/Tari_Legu_Sahu",
    "https://id.wikipedia.org/wiki/Tarian_Tide-tide",
    "https://id.wikipedia.org/wiki/Kukuhana",
    "https://id.wikipedia.org/wiki/Sasadu",
    "https://id.wikipedia.org/wiki/Yangere",
    "https://id.wikipedia.org/wiki/Rion-rion",
    "https://id.wikipedia.org/wiki/Laka_Baka",
    "https://id.wikipedia.org/wiki/Bela_Yai",
    "https://id.wikipedia.org/wiki/Tari_Togal",
    "https://id.wikipedia.org/wiki/Tari_Lala",
    "https://id.wikipedia.org/wiki/Bahasa_Bacan"
}

papua_urls = {
    "https://id.wikipedia.org/wiki/Yosim_Pancar",
    "https://id.wikipedia.org/wiki/Ukiran_Asmat",
    "https://id.wikipedia.org/wiki/Noken",
    "https://id.wikipedia.org/wiki/Tomako_Batu",
    "https://id.wikipedia.org/wiki/Koteka",
    "https://id.wikipedia.org/wiki/Tradisi_Wor",
    "https://id.wikipedia.org/wiki/Elha",
    "https://id.wikipedia.org/wiki/Aker",
    "https://id.wikipedia.org/wiki/Rumah_Honai",
    "https://id.wikipedia.org/wiki/Khombow",
    "https://id.wikipedia.org/wiki/Terfo",
    "https://id.wikipedia.org/wiki/Ndambu",
    "https://id.wikipedia.org/wiki/Yu",
    "https://id.wikipedia.org/wiki/Pokem",
    "https://id.wikipedia.org/wiki/Aimaro_Hena_Taje",
    "https://id.wikipedia.org/wiki/Bhukere",
    "https://id.wikipedia.org/wiki/Sirew",
    "https://id.wikipedia.org/wiki/Snap_Mor",
    "https://id.wikipedia.org/wiki/Akonipuk",
    "https://id.wikipedia.org/wiki/Helaehili",
    "https://id.wikipedia.org/wiki/Karamo",
    "https://id.wikipedia.org/wiki/Mbitoro",
    "https://id.wikipedia.org/wiki/Patung_Karwar"
}

papua_barat_urls = {
    "https://id.wikipedia.org/wiki/Papeda",
    "https://id.wikipedia.org/wiki/Rumput_kebar",
    "https://id.wikipedia.org/wiki/Fararior",
    "https://id.wikipedia.org/wiki/Kuk_kir_kna",
    "https://id.wikipedia.org/wiki/Mansorandak",
    "https://id.wikipedia.org/wiki/Anu_Beta_Tubat",
    "https://id.wikipedia.org/wiki/Orok"
}

province_culture_urls = {
    "ACEH" : aceh_urls,
    "SUMATERA UTARA" : sumatera_utara_urls,
    "SUMATERA BARAT" : sumatera_barat_urls,
    "RIAU" : riau_place_urls,
    "KEPULAUAN RIAU" : kepulauan_riau_urls,
    "JAMBI" : jambi_urls,
    "SUMATERA SELATAN" : sumatera_selatan_urls,
    "LAMPUNG" : lampung_urls,
    "BENGKULU" : bengkulu_urls,
    "BANGKA BELITUNG" : bangka_belitung_urls,
    "GORONTALO" : gorontalo_urls,
    "DKI JAKARTA" : dki_jakarta_urls,
    "JAWA BARAT" : jawa_barat_urls,
    "BANTEN" : banten_urls,
    "JAWA TENGAH" : jawa_tengah_urls,
    "DI YOGYAKARTA" : yogyakarta_urls,
    "JAWA TIMUR" : jawa_timur_urls,
    "BALI" : bali_urls,
    "NUSA TENGGARA BARAT" : nusa_tenggara_barat_urls,
    "NUSA TENGGARA TIMUR" : nusa_tenggara_timur_urls,
    "KALIMANTAN BARAT" : kalimantan_barat_urls,
    "KALIMANTAN SELATAN" : kalimantan_selatan_urls,
    "KALIMANTAN TENGAH" : kalimantan_tengah_urls,
    "KALIMANTAN TIMUR" : kalimantan_timur_urls,
    "KALIMANTAN UTARA" : kalimantan_utara_urls,
    "SULAWESI SELATAN" : sulawesi_selatan_urls,
    "SULAWESI UTARA" : sulawesi_utara_urls,
    "SULAWESI TENGGARA" : sulawesi_tenggara_urls,
    "SULAWESI TENGAH" : sulawesi_tengah_urls,
    "SULAWESI BARAT" : sulawesi_barat_urls,
    "MALUKU" : maluku_urls,
    "MALUKU UTARA" : maluku_utara_urls,
    "PAPUA" : papua_urls,
    "PAPUA BARAT" : papua_barat_urls,
}
