aceh_urls = {
    "https://id.wikipedia.org/wiki/Ayam_Tangkap",
    "https://id.wikipedia.org/wiki/Bada_Reuteuk",
    "https://id.wikipedia.org/wiki/Boh_Puniaram",
    "https://id.wikipedia.org/wiki/Dalca",
    "https://id.wikipedia.org/wiki/Kanji_Rumbi",
    "https://id.wikipedia.org/wiki/Keukarah",
    "https://id.wikipedia.org/wiki/Keumamah",
    "https://id.wikipedia.org/wiki/Kuwah_eungk%C3%B4t_y%C3%A8e",
    "https://id.wikipedia.org/wiki/Kuwah_it%C3%A9k",
    "https://id.wikipedia.org/wiki/Kuwah_pliek_u",
    "https://id.wikipedia.org/wiki/Kuwah_beulangong",
    "https://id.wikipedia.org/wiki/Kolak",
    "https://id.wikipedia.org/wiki/Martabak_Aceh",
    "https://id.wikipedia.org/wiki/Masam_Keu%27eueng",
    "https://id.wikipedia.org/wiki/Meuseukat",
    "https://id.wikipedia.org/wiki/Mie_Aceh",
    "https://id.wikipedia.org/wiki/Nasi_guri",
    "https://id.wikipedia.org/wiki/Roti_canai",
    "https://id.wikipedia.org/wiki/Roti_jala",
    "https://id.wikipedia.org/wiki/Sambai_asam_udeueng",
    "https://id.wikipedia.org/wiki/Sate_Matang",
    "https://id.wikipedia.org/wiki/Sie_Reuboh",
    "https://id.wikipedia.org/wiki/Timphan",
    "https://id.wikipedia.org/wiki/Wajik",
    "https://id.wikipedia.org/wiki/Lompong_Sagu",
    "https://id.wikipedia.org/wiki/Masam_Jing",
    "https://id.wikipedia.org/wiki/Pengat",
}

sumatera_utara_urls = {
"https://id.wikipedia.org/wiki/Angsle",
    "https://id.wikipedia.org/wiki/Arsik",
    "https://id.wikipedia.org/wiki/Babi_Panggang_Karo",
    "https://id.wikipedia.org/wiki/Bika_Ambon",
    "https://id.wikipedia.org/wiki/Bolu_Gulung",
    "https://id.wikipedia.org/wiki/Bubur_pedas",
    "https://id.wikipedia.org/wiki/Bulung_Gadung",
    "https://id.wikipedia.org/wiki/Cimpa",
    "https://id.wikipedia.org/wiki/Cipera",
    "https://id.wikipedia.org/wiki/Dalini_Horbo",
    "https://id.wikipedia.org/wiki/Kuwah_eungk%C3%B4t_y%C3%A8e",
    "https://id.wikipedia.org/wiki/Manisan_buah",
    "https://id.wikipedia.org/wiki/Holat",
    "https://id.wikipedia.org/wiki/Ikan_asap",
    "https://id.wikipedia.org/wiki/Kwetiau",
    "https://id.wikipedia.org/wiki/Lapis_Legit",
    "https://id.wikipedia.org/wiki/Katimus",
    "https://id.wikipedia.org/wiki/Lappet_Pohul-pohul",
    "https://id.wikipedia.org/wiki/Lappet",
    "https://id.wikipedia.org/wiki/Lemang",
    "https://id.wikipedia.org/wiki/Mie_Gomak",
    "https://id.wikipedia.org/wiki/Naniura",
    "https://id.wikipedia.org/wiki/Ombus-Ombus",
    "https://id.wikipedia.org/wiki/Pangsit",
    "https://id.wikipedia.org/wiki/Pisang_Molen",
    "https://id.wikipedia.org/wiki/Pok_pia",
    "https://id.wikipedia.org/wiki/Roti_ketawa",
    "https://id.wikipedia.org/wiki/Saksang",
    "https://id.wikipedia.org/wiki/Sambal_Rias",
    "https://id.wikipedia.org/wiki/Sambal_Andaliman",
    "https://id.wikipedia.org/wiki/Sambal_Tuk_Tuk",
    "https://id.wikipedia.org/wiki/Sambal_Gota",
    "https://id.wikipedia.org/wiki/Sangsang",
    "https://id.wikipedia.org/wiki/Soto_Medan",
    "https://id.wikipedia.org/wiki/Tanggotanggo",
    "https://id.wikipedia.org/wiki/Pagit-pagit",
    "https://id.wikipedia.org/wiki/Tipa-tipa",
    "https://id.wikipedia.org/wiki/Panggang_Geleng",
    "https://id.wikipedia.org/wiki/Tuak",
}

sumatera_barat_urls = {
    "https://id.wikipedia.org/wiki/Ale-ale",
    "https://id.wikipedia.org/wiki/Asam_pedas",
    "https://id.wikipedia.org/wiki/Ayam_pop",
    "https://id.wikipedia.org/wiki/Beras_rendang",
    "https://id.wikipedia.org/wiki/Bika",
    "https://id.wikipedia.org/wiki/Bubur_kampiun",
    "https://id.wikipedia.org/wiki/Cendol",
    "https://id.wikipedia.org/wiki/Dadiah",
    "https://id.wikipedia.org/wiki/Dendeng_balado",
    "https://id.wikipedia.org/wiki/Dendeng_batokok",
    "https://id.wikipedia.org/wiki/Gajebo",
    "https://id.wikipedia.org/wiki/Galamai",
    "https://id.wikipedia.org/wiki/Godok_Obuih",
    "https://id.wikipedia.org/wiki/Gulai_banak",
    "https://id.wikipedia.org/wiki/Pangek_cubadak",
    "https://id.wikipedia.org/wiki/Gulai_itiak",
    "https://id.wikipedia.org/wiki/Gulai_paku",
    "https://id.wikipedia.org/wiki/Tambunsu",
    "https://id.wikipedia.org/wiki/Gulai",
    "https://id.wikipedia.org/wiki/Kalio",
    "https://id.wikipedia.org/wiki/Keripik_sanjai",
    "https://id.wikipedia.org/wiki/Karupuak_jangek",
    "https://id.wikipedia.org/wiki/Karupuak_jariang",
    "https://id.wikipedia.org/wiki/Ketan_durian",
    "https://id.wikipedia.org/wiki/Katan_sarikayo",
    "https://id.wikipedia.org/wiki/Kipang",
    "https://id.wikipedia.org/wiki/Kipang_kacang",
    "https://id.wikipedia.org/wiki/Lamang_tapai",
    "https://id.wikipedia.org/wiki/Lapek_bugih",
    "https://id.wikipedia.org/wiki/Lemang",
    "https://id.wikipedia.org/wiki/Martabak_mesir",
    "https://id.wikipedia.org/wiki/Nasi_kapau",
    "https://id.wikipedia.org/wiki/Palai_bada",
    "https://id.wikipedia.org/wiki/Pangek_masin",
    "https://id.wikipedia.org/wiki/Perkedel",
    "https://id.wikipedia.org/wiki/Pinyaram",
    "https://id.wikipedia.org/wiki/Rendang",
    "https://id.wikipedia.org/wiki/Samba_lado_tanak",
    "https://id.wikipedia.org/wiki/Sate_Padang",
    "https://id.wikipedia.org/wiki/Sate_Pariaman",
    "https://id.wikipedia.org/wiki/Serabi",
    "https://id.wikipedia.org/wiki/Soto_Padang",
    "https://id.wikipedia.org/wiki/Wajik",
}

riau_place_urls = {
    "https://id.wikipedia.org/wiki/Anyang",
    "https://id.wikipedia.org/wiki/Bubur_lambok",
    "https://id.wikipedia.org/wiki/Telur_dadar_tiram",
    "https://id.wikipedia.org/wiki/Kemi",
    "https://id.wikipedia.org/wiki/Kwetiau_Bagan",
    "https://id.wikipedia.org/wiki/Mi_sagu",
    "https://id.wikipedia.org/wiki/Sempolet",
}

kepulauan_riau_urls = {
    "https://id.wikipedia.org/wiki/Asam_pedas",
    "https://id.wikipedia.org/wiki/Cincalok",
    "https://id.wikipedia.org/wiki/Kernas",
    "https://id.wikipedia.org/wiki/Laksa",
    "https://id.wikipedia.org/wiki/Lempeng",
    "https://id.wikipedia.org/wiki/Mi_lendir",
    "https://id.wikipedia.org/wiki/Mi_Tarempa",
    "https://id.wikipedia.org/wiki/Mi_sagu",
    "https://id.wikipedia.org/wiki/Nasi_dagang",
    "https://id.wikipedia.org/wiki/Nasi_Lemak",
    "https://id.wikipedia.org/wiki/Roti_canai",
    "https://id.wikipedia.org/wiki/Roti_jala",
    "https://id.wikipedia.org/wiki/Tabel_mando",
}

jambi_urls = {
    "https://id.wikipedia.org/wiki/Brengkes_Tempoyak",
    "https://id.wikipedia.org/wiki/Daging_masak_hitam",
    "https://id.wikipedia.org/wiki/Gelamai_Perentak",
    "https://id.wikipedia.org/wiki/Gulai_belut",
    "https://id.wikipedia.org/wiki/Gulai_Ikan_Semah_(Khas_Merangin)",
    "https://id.wikipedia.org/wiki/Gulai_Tekuyung",
    "https://id.wikipedia.org/wiki/Gulai_tepek_ikan",
    "https://id.wikipedia.org/wiki/Gulai_terjun_daging",
    "https://id.wikipedia.org/wiki/Kerutup_ikan",
    "https://id.wikipedia.org/wiki/Lemang",
    "https://id.wikipedia.org/wiki/Nasi_gemuk",
    "https://id.wikipedia.org/wiki/Nasi_lemak",
    "https://id.wikipedia.org/wiki/Pempek_sambal",
    "https://id.wikipedia.org/wiki/Rendang",
    "https://id.wikipedia.org/wiki/Sambal_Salabance",
    "https://id.wikipedia.org/wiki/Tempoyak",
    "https://id.wikipedia.org/wiki/Bagar_hiu",
    "https://id.wikipedia.org/wiki/Pakasam",
    "https://id.wikipedia.org/wiki/Lema_(makanan)",
    "https://id.wikipedia.org/wiki/Pendap",
    "https://id.wikipedia.org/wiki/Tempoyak",
}

sumatera_selatan_urls = {
    "https://id.wikipedia.org/wiki/Brengkes_Tempoyak",
    "https://id.wikipedia.org/wiki/Bolu_Kojo",
    "https://id.wikipedia.org/wiki/Burgo",
    "https://id.wikipedia.org/wiki/Ikan_Salai",
    "https://id.wikipedia.org/wiki/Kemplang",
    "https://id.wikipedia.org/wiki/Kue_satu",
    "https://id.wikipedia.org/wiki/Kue_maksuba",
    "https://id.wikipedia.org/wiki/Laksa",
    "https://id.wikipedia.org/wiki/Mie_Celor",
    "https://id.wikipedia.org/wiki/Model",
    "https://id.wikipedia.org/wiki/Nasi_Lemak",
    "https://id.wikipedia.org/wiki/Nasi_Minyak",
    "https://id.wikipedia.org/wiki/Otak-otak",
    "https://id.wikipedia.org/wiki/Tekwan",
}

lampung_urls = {
    "https://id.wikipedia.org/wiki/Gulai_Balak",
    "https://id.wikipedia.org/wiki/Gulai_Taboh",
    "https://id.wikipedia.org/wiki/Keripik_Pisang",
    "https://id.wikipedia.org/wiki/Sekubal",
}

bengkulu_urls = {
    "https://id.wikipedia.org/wiki/Kelicuk",
}

bangka_belitung_urls = {

}

gorontalo_urls = {
    "https://id.wikipedia.org/wiki/Ayam_iloni",
    "https://id.wikipedia.org/wiki/Binte_Biluhuta",
    "https://id.wikipedia.org/wiki/Ikan_iloni",
    "https://id.wikipedia.org/wiki/Sagela",
    "https://id.wikipedia.org/wiki/Ilabulo",
    "https://id.wikipedia.org/wiki/Pilitode",
    "https://id.wikipedia.org/wiki/Bilentango",
    "https://id.wikipedia.org/wiki/Sate_balanga",
    "https://id.wikipedia.org/wiki/Sate_Gorontalo",
    "https://id.wikipedia.org/wiki/Barlian",
    "https://id.wikipedia.org/wiki/Pisang_goroho",
    "https://id.wikipedia.org/wiki/Sukade",
}

dki_jakarta_urls = {
    "https://id.wikipedia.org/wiki/Bir_Pletok",
    "https://id.wikipedia.org/wiki/Emping",
    "https://id.wikipedia.org/wiki/Es_selendang_mayang",
    "https://id.wikipedia.org/wiki/Gado-gado",
    "https://id.wikipedia.org/wiki/Geplak",
    "https://id.wikipedia.org/wiki/Kerak_Telor",
    "https://id.wikipedia.org/wiki/Ketoprak_(makanan)",
    "https://id.wikipedia.org/wiki/Kroket",
    "https://id.wikipedia.org/wiki/Kue_akar_kelapa",
    "https://id.wikipedia.org/wiki/Kue_ape",
    "https://id.wikipedia.org/wiki/Kue_Bakar",
    "https://id.wikipedia.org/wiki/Kue_jongkong",
    "https://id.wikipedia.org/wiki/Mi_kangkung",
    "https://id.wikipedia.org/wiki/Nasi_kebuli",
    "https://id.wikipedia.org/wiki/Nasi_Uduk",
    "https://id.wikipedia.org/wiki/Onde-onde",
    "https://id.wikipedia.org/wiki/Ongol-Ongol",
    "https://id.wikipedia.org/wiki/Pelas",
    "https://id.wikipedia.org/wiki/Risoles",
    "https://id.wikipedia.org/wiki/Roti_Buaya",
    "https://id.wikipedia.org/wiki/Sayur_Besan",
    "https://id.wikipedia.org/wiki/Semur_Jengkol",
    "https://id.wikipedia.org/wiki/Soto_Betawi",
    "https://id.wikipedia.org/wiki/Soto_mie",
    "https://id.wikipedia.org/wiki/Soto_Tangkar",
}

jawa_barat_urls = {
    "https://id.wikipedia.org/wiki/Ambokueh",
    "https://id.wikipedia.org/wiki/Bajigur",
    "https://id.wikipedia.org/wiki/Bandrek",
    "https://id.wikipedia.org/wiki/Batagor",
    "https://id.wikipedia.org/wiki/Cireng",
    "https://id.wikipedia.org/wiki/Colenak",
    "https://id.wikipedia.org/wiki/Combro",
    "https://id.wikipedia.org/wiki/Cuanki",
    "https://id.wikipedia.org/wiki/Gehu_(makanan)",
    "https://id.wikipedia.org/wiki/Gepuk",
    "https://id.wikipedia.org/wiki/Karedok",
    "https://id.wikipedia.org/wiki/Kolontong",
    "https://id.wikipedia.org/wiki/Kue_Sus",
    "https://id.wikipedia.org/wiki/Lotek",
    "https://id.wikipedia.org/wiki/Mi_Kocok",
    "https://id.wikipedia.org/wiki/Misro",
    "https://id.wikipedia.org/wiki/Nasi_Timbel",
    "https://id.wikipedia.org/wiki/Peuyeum",
    "https://id.wikipedia.org/wiki/Pisang_Molen",
    "https://id.wikipedia.org/wiki/Seblak",
    "https://id.wikipedia.org/wiki/Serabi",
    "https://id.wikipedia.org/wiki/Siomay",
    "https://id.wikipedia.org/wiki/Soto_Bandung",
    "https://id.wikipedia.org/wiki/Kue_Cubit",
    "https://id.wikipedia.org/wiki/Tahu_bulat",
    "https://id.wikipedia.org/wiki/Tahu_Sumedang",
    "https://id.wikipedia.org/wiki/Tauco",
    "https://id.wikipedia.org/wiki/Kupat_Tahu",
    "https://id.wikipedia.org/wiki/Nasi_Tutug_Oncom",
    "https://id.wikipedia.org/wiki/Tahu_Bulat",
    "https://id.wikipedia.org/wiki/Kupat_Tahu",
    "https://id.wikipedia.org/wiki/Pindang_Tetel",
    "https://id.wikipedia.org/wiki/Hucap",
    "https://id.wikipedia.org/wiki/Dodol_Garut",
    "https://id.wikipedia.org/wiki/Dorokdok",
    "https://id.wikipedia.org/wiki/Ladu",
    "https://id.wikipedia.org/wiki/Docang",
    "https://id.wikipedia.org/wiki/Empal_Gentong",
    "https://id.wikipedia.org/wiki/Mi_koclok",
    "https://id.wikipedia.org/wiki/Sega_Jamblang",
    "https://id.wikipedia.org/wiki/Sega_Lengko",
    "https://id.wikipedia.org/wiki/Tahu_Gejrot",
    "https://id.wikipedia.org/wiki/Soto_Kuning",
    "https://id.wikipedia.org/wiki/Doclang",
    "https://id.wikipedia.org/wiki/Ayam_Goreng",
    "https://id.wikipedia.org/wiki/Bubur_ayam",
    "https://id.wikipedia.org/wiki/Mochi",
    "https://id.wikipedia.org/wiki/Pepes",
    "https://id.wikipedia.org/wiki/Colenak",
    "https://id.wikipedia.org/wiki/Opak",
    "https://id.wikipedia.org/wiki/Sate_Maranggi",
    "https://id.wikipedia.org/wiki/Simping_(makanan)",
}

banten_urls = {
    "https://id.wikipedia.org/wiki/Ayam_bekakak",
    "https://id.wikipedia.org/wiki/Emping",
    "https://id.wikipedia.org/wiki/Gemblong",
    "https://id.wikipedia.org/wiki/Jojorong",
    "https://id.wikipedia.org/wiki/Otak-otak",
    "https://id.wikipedia.org/wiki/Rabeg",
    "https://id.wikipedia.org/wiki/Semur",
}

jawa_tengah_urls = {
    "https://id.wikipedia.org/wiki/Es_puter",
    "https://id.wikipedia.org/wiki/Gandos",
    "https://id.wikipedia.org/wiki/Gudangan",
    "https://id.wikipedia.org/wiki/Lumpia_Semarang",
    "https://id.wikipedia.org/wiki/Mi_kopyok",
    "https://id.wikipedia.org/wiki/Nasi_Gandul",
    "https://id.wikipedia.org/wiki/Roti_Ganjel_Rel",
    "https://id.wikipedia.org/wiki/Soto_Semarang",
    "https://id.wikipedia.org/wiki/Tahu_Gimbal",
    "https://id.wikipedia.org/wiki/Kupat_tahu",
    "https://id.wikipedia.org/wiki/Tahu_Bakso",
    "https://id.wikipedia.org/wiki/Soto_Petanahan",
    "https://id.wikipedia.org/wiki/Tongseng",
    "https://id.wikipedia.org/wiki/Sate_Ambal",
    "https://id.wikipedia.org/wiki/Ciwel",
    "https://id.wikipedia.org/wiki/Lupis",
    "https://id.wikipedia.org/wiki/Cenil",
    "https://id.wikipedia.org/wiki/Jipang",
    "https://id.wikipedia.org/wiki/Dawet_Ireng",
    "https://id.wikipedia.org/wiki/Arem-arem",
    "https://id.wikipedia.org/wiki/Kamir",
    "https://id.wikipedia.org/wiki/Lontong_Dekem",
    "https://id.wikipedia.org/wiki/Ogel-Ogel",
    "https://id.wikipedia.org/wiki/Nasi_Grombyang",
    "https://id.wikipedia.org/wiki/Nasi_Megono",
    "https://id.wikipedia.org/wiki/Enting-enting",
    "https://id.wikipedia.org/wiki/Getuk",
    "https://id.wikipedia.org/wiki/Sumpil",
    "https://id.wikipedia.org/wiki/Cotot",
    "https://id.wikipedia.org/wiki/Kupat_Tahu",
    "https://id.wikipedia.org/wiki/Wajik",
    "https://id.wikipedia.org/wiki/Nagasari",
    "https://id.wikipedia.org/wiki/Nasi_Jagung",
    "https://id.wikipedia.org/wiki/Mendoan",
    "https://id.wikipedia.org/wiki/Pecel_Gendar",
    "https://id.wikipedia.org/wiki/Soto_Ayam",
    "https://id.wikipedia.org/wiki/Tepo",
    "https://id.wikipedia.org/wiki/Lengko",
    "https://id.wikipedia.org/wiki/Olos",
    "https://id.wikipedia.org/wiki/Pilus",
    "https://id.wikipedia.org/wiki/Sate_Tegal",
    "https://id.wikipedia.org/wiki/Tahu_Aci",
    "https://id.wikipedia.org/wiki/Telur_Asin_Brebes",
    "https://id.wikipedia.org/wiki/Sroto_Kriyik",
    "https://id.wikipedia.org/wiki/Sroto_Bancar",
    "https://id.wikipedia.org/wiki/Sate_Blater",
    "https://id.wikipedia.org/wiki/Nopia",
    "https://id.wikipedia.org/wiki/Getuk_goreng",
    "https://id.wikipedia.org/wiki/Mino",
    "https://id.wikipedia.org/wiki/Soto_Sokaraja",
    "https://id.wikipedia.org/wiki/Tempe_mendoan",
    "https://id.wikipedia.org/wiki/Bakmi_Nyemek",
    "https://id.wikipedia.org/wiki/Cimplung",
    "https://id.wikipedia.org/wiki/Getuk",
    "https://id.wikipedia.org/wiki/Tegean",
    "https://id.wikipedia.org/wiki/Lontong_sayur",
    "https://id.wikipedia.org/wiki/Nasi_Megono",
    "https://id.wikipedia.org/wiki/Soto_Pekalongan",
    "https://id.wikipedia.org/wiki/Pindang_Tetel",
    "https://id.wikipedia.org/wiki/Tauto",
    "https://id.wikipedia.org/wiki/Adon-Adon_Coro",
    "https://id.wikipedia.org/wiki/Carang_Madu",
    "https://id.wikipedia.org/wiki/Rujak_Degan_Jepara",
    "https://id.wikipedia.org/wiki/Es_Dawet",
    "https://id.wikipedia.org/wiki/Es_Gempol",
    "https://id.wikipedia.org/wiki/Horok-Horok",
    "https://id.wikipedia.org/wiki/Kacang_Jepara",
    "https://id.wikipedia.org/wiki/Kacang_Oven",
    "https://id.wikipedia.org/wiki/Keciput",
    "https://id.wikipedia.org/wiki/Kerupuk_Kerapu",
    "https://id.wikipedia.org/wiki/Kue_bangkit",
    "https://id.wikipedia.org/wiki/Nasi_tempong",
    "https://id.wikipedia.org/wiki/Pecel_Ikan_Laut_Panggang",
    "https://id.wikipedia.org/wiki/Pindang_Serani",
    "https://id.wikipedia.org/wiki/Sate_Kikil",
    "https://id.wikipedia.org/wiki/Sop_Udang",
    "https://id.wikipedia.org/wiki/Soto_Jepara",
    "https://id.wikipedia.org/wiki/Krecek",
    "https://id.wikipedia.org/wiki/Cenil",
    "https://id.wikipedia.org/wiki/Bandeng_presto",
    "https://id.wikipedia.org/wiki/Nasi_gandul",
    "https://id.wikipedia.org/wiki/Soto_kemiri",
    "https://id.wikipedia.org/wiki/Petis_runting",
    "https://id.wikipedia.org/wiki/Getuk",
    "https://id.wikipedia.org/wiki/Lupis_(makanan)",
    "https://id.wikipedia.org/wiki/Garang_Asem",
    "https://id.wikipedia.org/wiki/Jenang_kudus",
    "https://id.wikipedia.org/wiki/Lentog",
    "https://id.wikipedia.org/wiki/Nasi_Grombyang",
    "https://id.wikipedia.org/wiki/Nasi_megono",
    "https://id.wikipedia.org/wiki/Nasi_pindang",
    "https://id.wikipedia.org/wiki/Soto_Kudus",
    "https://id.wikipedia.org/wiki/Pecel_Pakis",
    "https://id.wikipedia.org/wiki/Clorot",
    "https://id.wikipedia.org/wiki/Gula_Semut",
    "https://id.wikipedia.org/wiki/Uli",
    "https://id.wikipedia.org/wiki/Kaoya_dudul",
    "https://id.wikipedia.org/wiki/Kerupuk_bakar",
    "https://id.wikipedia.org/wiki/Lontong_Tuyuhan",
    "https://id.wikipedia.org/wiki/Rawon",
    "https://id.wikipedia.org/wiki/Asem-Asem_Daging",
    "https://id.wikipedia.org/wiki/Botok_Telur_Asin",
    "https://id.wikipedia.org/wiki/Nasi_Ndoreng",
    "https://id.wikipedia.org/wiki/Wedang_Pekak",
    "https://id.wikipedia.org/wiki/Momoh",
    "https://id.wikipedia.org/wiki/Ampyang",
    "https://id.wikipedia.org/wiki/Carang_Gesing",
    "https://id.wikipedia.org/wiki/Dawet_Ayu",
    "https://id.wikipedia.org/wiki/Dawet",
    "https://id.wikipedia.org/wiki/Garang_Asem",
    "https://id.wikipedia.org/wiki/Gudeg",
}

yogyakarta_urls = {
    "https://id.wikipedia.org/wiki/Abangan",
    "https://id.wikipedia.org/wiki/Alen-alen",
    "https://id.wikipedia.org/wiki/Ampyang",
    "https://id.wikipedia.org/wiki/Ayam_Geprek",
    "https://id.wikipedia.org/wiki/Bakmi_Jawa",
    "https://id.wikipedia.org/wiki/Bakpia",
    "https://id.wikipedia.org/wiki/Bolu_emprit",
    "https://id.wikipedia.org/wiki/Carang_Gesing",
    "https://id.wikipedia.org/wiki/Cenil",
    "https://id.wikipedia.org/wiki/Enting-enting",
    "https://id.wikipedia.org/wiki/Gado-Gado",
    "https://id.wikipedia.org/wiki/Gaplek",
    "https://id.wikipedia.org/wiki/Gatot",
    "https://id.wikipedia.org/wiki/Geplak",
    "https://id.wikipedia.org/wiki/Getuk",
    "https://id.wikipedia.org/wiki/Growol",
    "https://id.wikipedia.org/wiki/Gudangan",
    "https://id.wikipedia.org/wiki/Gudeg",
    "https://id.wikipedia.org/wiki/Gudeg_Manggar",
    "https://id.wikipedia.org/wiki/Jadah_Manten",
    "https://id.wikipedia.org/wiki/Juwawut",
    "https://id.wikipedia.org/wiki/Kipo",
    "https://id.wikipedia.org/wiki/Klepon",
    "https://id.wikipedia.org/wiki/Mendut",
    "https://id.wikipedia.org/wiki/Nasi_Kucing",
    "https://id.wikipedia.org/wiki/Nasi_Pecel",
    "https://id.wikipedia.org/wiki/Onde-onde",
    "https://id.wikipedia.org/wiki/Ongol-ongol",
    "https://id.wikipedia.org/wiki/Opor_Ayam",
    "https://id.wikipedia.org/wiki/Pecel",
    "https://id.wikipedia.org/wiki/Rengginang",
    "https://id.wikipedia.org/wiki/Sate_Klathak",
    "https://id.wikipedia.org/wiki/Selat",
    "https://id.wikipedia.org/wiki/Semar_Mesem",
    "https://id.wikipedia.org/wiki/Timus",
    "https://id.wikipedia.org/wiki/Tiwul",
    "https://id.wikipedia.org/wiki/Tongseng",
    "https://id.wikipedia.org/wiki/Trancam",
    "https://id.wikipedia.org/wiki/Tumpeng",
    "https://id.wikipedia.org/wiki/Urap",
    "https://id.wikipedia.org/wiki/Wajik",
    "https://id.wikipedia.org/wiki/Ronde_(makanan)",
    "https://id.wikipedia.org/wiki/Wedang_Secang",
    "https://id.wikipedia.org/wiki/Wedang_Uwuh",
    "https://id.wikipedia.org/wiki/Yangko",
}

jawa_timur_urls = {
    "https://id.wikipedia.org/wiki/Rawon",
    "https://id.wikipedia.org/wiki/Lontong_Balap",
    "https://id.wikipedia.org/wiki/Bebek_goreng",
    "https://id.wikipedia.org/wiki/Krengsengan",
    "https://id.wikipedia.org/wiki/Rujak_Cingur",
    "https://id.wikipedia.org/wiki/Semanggi_(makanan)",
    "https://id.wikipedia.org/wiki/Tahu_Tek",
    "https://id.wikipedia.org/wiki/Kue_cucur",
    "https://id.wikipedia.org/wiki/Lontong_Kupang",
    "https://id.wikipedia.org/wiki/Sate_kerang",
    "https://id.wikipedia.org/wiki/Kerupuk_udang",
    "https://id.wikipedia.org/wiki/Bandeng_asap",
    "https://id.wikipedia.org/wiki/Bandeng_presto",
    "https://id.wikipedia.org/wiki/Petis",
    "https://id.wikipedia.org/wiki/Lontong_balap",
    "https://id.wikipedia.org/wiki/Kupang_Lontong",
    "https://id.wikipedia.org/wiki/Weci",
    "https://id.wikipedia.org/wiki/Menjes",
    "https://id.wikipedia.org/wiki/Onde-onde",
    "https://id.wikipedia.org/wiki/Nasi_Pecel",
    "https://id.wikipedia.org/wiki/Soto_Lamongan",
    "https://id.wikipedia.org/wiki/Tahu_campur",
    "https://id.wikipedia.org/wiki/Tahu_Tek",
    "https://id.wikipedia.org/wiki/Wingko_Babat",
    "https://id.wikipedia.org/wiki/Tiwul",
    "https://id.wikipedia.org/wiki/Soto_Kediri",
    "https://id.wikipedia.org/wiki/Tahu_Kuning",
    "https://id.wikipedia.org/wiki/Gethuk_Pisang",
    "https://id.wikipedia.org/wiki/Sate_Bekicot",
    "https://id.wikipedia.org/wiki/Rujak_Soto",
    "https://id.wikipedia.org/wiki/Bothok",
    "https://id.wikipedia.org/wiki/Lemper",
    "https://id.wikipedia.org/wiki/Bungkuk",
    "https://id.wikipedia.org/wiki/Lemet",
    "https://id.wikipedia.org/wiki/Lanun",
    "https://id.wikipedia.org/wiki/Lupis",
    "https://id.wikipedia.org/wiki/Jemblem",
    "https://id.wikipedia.org/wiki/Pukis",
    "https://id.wikipedia.org/wiki/Rujak_Petis",
    "https://id.wikipedia.org/wiki/Rujak_Manis",
    "https://id.wikipedia.org/wiki/Pare",
    "https://id.wikipedia.org/wiki/Pecel_Madiun",
    "https://id.wikipedia.org/wiki/Brem",
    "https://id.wikipedia.org/wiki/Lempeng",
    "https://id.wikipedia.org/wiki/Gado_Gado",
    "https://id.wikipedia.org/wiki/Rawon",
    "https://id.wikipedia.org/wiki/Lepet_Jagung",
    "https://id.wikipedia.org/wiki/Bakso_Malang",
    "https://id.wikipedia.org/wiki/Keripik_Kentang",
    "https://id.wikipedia.org/wiki/Keripik_Singkong",
    "https://id.wikipedia.org/wiki/Keripik_Tempe",
    "https://id.wikipedia.org/wiki/Angsle",
    "https://id.wikipedia.org/wiki/Rujak_Cingur",
    "https://id.wikipedia.org/wiki/Tahu_Tek",
    "https://id.wikipedia.org/wiki/Ronde",
    "https://id.wikipedia.org/wiki/Mendol",
    "https://id.wikipedia.org/wiki/Nasi_Krawu",
    "https://id.wikipedia.org/wiki/Tempe_Penyet",
    "https://id.wikipedia.org/wiki/Sego_Tempong",
    "https://id.wikipedia.org/wiki/Nasi_Boranan",
    "https://id.wikipedia.org/wiki/Nasi_Becek",
    "https://id.wikipedia.org/wiki/Keripik_Tempe",
    "https://id.wikipedia.org/wiki/Tape",
    "https://id.wikipedia.org/wiki/Suwar-suwir",
    "https://id.wikipedia.org/wiki/Gulai",
    "https://id.wikipedia.org/wiki/Gangsa",
    "https://id.wikipedia.org/wiki/Klepon",
    "https://id.wikipedia.org/wiki/Sate",
    "https://id.wikipedia.org/wiki/Sate_lalat",
    "https://id.wikipedia.org/wiki/Lepet",
    "https://id.wikipedia.org/wiki/Soto_Madura",
    "https://id.wikipedia.org/wiki/Nasi_Jagung",
    "https://id.wikipedia.org/wiki/Pelas",
    "https://id.wikipedia.org/wiki/Ampo",
    "https://id.wikipedia.org/wiki/Keripik_Pisang",
    "https://id.wikipedia.org/wiki/Sale_Pisang",
    "https://id.wikipedia.org/wiki/Bajingan",
    "https://id.wikipedia.org/wiki/Kolong_Klitik",
}

bali_urls = {
    "https://id.wikipedia.org/wiki/Ayam_Betutu",
    "https://id.wikipedia.org/wiki/Babi_Guling",
    "https://id.wikipedia.org/wiki/Bandot",
    "https://id.wikipedia.org/wiki/Be_Pasih_Mesambel_Matah",
    "https://id.wikipedia.org/wiki/Garang_asem",
    "https://id.wikipedia.org/wiki/Srombotan",
    "https://id.wikipedia.org/wiki/Urap",
    "https://id.wikipedia.org/wiki/Lawar",
    "https://id.wikipedia.org/wiki/Sate_Lilit",
    "https://id.wikipedia.org/wiki/Sate_Penyu",
    "https://id.wikipedia.org/wiki/Srombotan",
    "https://id.wikipedia.org/wiki/Timbungan",
    "https://id.wikipedia.org/wiki/Nasi_Jenggo",
    "https://id.wikipedia.org/wiki/Urutan_(Masakan_Bali)",
    "https://id.wikipedia.org/wiki/Bubur_sumsum",
    "https://id.wikipedia.org/wiki/Jaja_Begina",
    "https://id.wikipedia.org/wiki/Jaja_Bendu",
    "https://id.wikipedia.org/wiki/Jaja_Klepon",
    "https://id.wikipedia.org/wiki/Jaja_Wajik",
    "https://id.wikipedia.org/wiki/Rujak_Kuah_Pindang",
    "https://id.wikipedia.org/wiki/Rujak_Manis",
}

nusa_tenggara_barat_urls = {
    "https://id.wikipedia.org/wiki/Salome",
    "https://id.wikipedia.org/wiki/Bingka_dolu",
    "https://id.wikipedia.org/wiki/Barongko",
    "https://id.wikipedia.org/wiki/Ayam_Taliwang",
    "https://id.wikipedia.org/wiki/Sate_Bulayak",
    "https://id.wikipedia.org/wiki/Plecing_Kangkung",
    "https://id.wikipedia.org/wiki/Beberuk_terong",
    "https://id.wikipedia.org/wiki/Ares",
    "https://id.wikipedia.org/wiki/Singang",
    "https://id.wikipedia.org/wiki/Ayam_Rarang",
    "https://id.wikipedia.org/wiki/Sate_Bulayak",
    "https://id.wikipedia.org/wiki/Sako",
    "https://id.wikipedia.org/wiki/Lada",
}

nusa_tenggara_timur_urls = {
    "https://id.wikipedia.org/wiki/Jagung_bose",
    "https://id.wikipedia.org/wiki/Jagung_titi",
    "https://id.wikipedia.org/wiki/Katemak",
    "https://id.wikipedia.org/wiki/Kolo",
    "https://id.wikipedia.org/wiki/Lori",
    "https://id.wikipedia.org/wiki/Nasi_kacang_merah",
    "https://id.wikipedia.org/wiki/Rumpu_rampe",
    "https://id.wikipedia.org/wiki/Se%27i",
    "https://id.wikipedia.org/wiki/Ubi_nuabosi",
}

kalimantan_barat_urls = {
    "https://id.wikipedia.org/wiki/Kerupuk_Basah",
    "https://id.wikipedia.org/wiki/Lemang",
    "https://id.wikipedia.org/wiki/Lidah_Buaya",
    "https://id.wikipedia.org/wiki/Tempoyak",
    "https://id.wikipedia.org/wiki/Bingka",
    "https://id.wikipedia.org/wiki/Bubur_gunting",
    "https://id.wikipedia.org/wiki/Kue_pasung",
    "https://id.wikipedia.org/wiki/Lempok",
}

kalimantan_selatan_urls = {
}

kalimantan_tengah_urls = {
    "https://id.wikipedia.org/wiki/Dami",
    "https://id.wikipedia.org/wiki/Kalumpe",
    "https://id.wikipedia.org/wiki/Lemang",
    "https://id.wikipedia.org/wiki/Paing",
    "https://id.wikipedia.org/wiki/Wadi",
}

kalimantan_timur_urls = {
}

kalimantan_utara_urls = {
    "https://id.wikipedia.org/wiki/Lawa",
    "https://id.wikipedia.org/wiki/Kepiting_soka",
    "https://id.wikipedia.org/wiki/Naul",
}

sulawesi_selatan_urls = {
    "https://id.wikipedia.org/wiki/Apam_paranggi",
    "https://id.wikipedia.org/wiki/Baje%27",
    "https://id.wikipedia.org/wiki/Barongko",
    "https://id.wikipedia.org/wiki/Bassang",
    "https://id.wikipedia.org/wiki/Bipang",
    "https://id.wikipedia.org/wiki/Bingka_barandam",
    "https://id.wikipedia.org/wiki/Nagasari",
    "https://id.wikipedia.org/wiki/Jalangkote",
    "https://id.wikipedia.org/wiki/Katerisallang",
    "https://id.wikipedia.org/wiki/Kue_Putu",
    "https://id.wikipedia.org/wiki/Ongol-ongol",
    "https://id.wikipedia.org/wiki/Pallu_Butung",
    "https://id.wikipedia.org/wiki/Pisang_peppe",
    "https://id.wikipedia.org/wiki/Pisang_Ijo",
    "https://id.wikipedia.org/wiki/Bakpao",
    "https://id.wikipedia.org/wiki/Gemblong",
    "https://id.wikipedia.org/wiki/Gogos",
    "https://id.wikipedia.org/wiki/Buras",
    "https://id.wikipedia.org/wiki/Coto_Makassar",
    "https://id.wikipedia.org/wiki/Dangke",
    "https://id.wikipedia.org/wiki/Ikan_rica",
    "https://id.wikipedia.org/wiki/Kapurung",
    "https://id.wikipedia.org/wiki/Lawa",
    "https://id.wikipedia.org/wiki/Pallu_Butung",
    "https://id.wikipedia.org/wiki/Pacco%27",
    "https://id.wikipedia.org/wiki/Sop_Kikil",
    "https://id.wikipedia.org/wiki/Sop_Konro",
    "https://id.wikipedia.org/wiki/Sop_Saudara",
    "https://id.wikipedia.org/wiki/Kawah",
}

sulawesi_utara_urls = {
    "https://id.wikipedia.org/wiki/Bagea",
    "https://id.wikipedia.org/wiki/Binyolos",
    "https://id.wikipedia.org/wiki/Bobengka",
    "https://id.wikipedia.org/wiki/Klappertaart",
    "https://id.wikipedia.org/wiki/Koyabu",
    "https://id.wikipedia.org/wiki/Lampu_lampu",
    "https://id.wikipedia.org/wiki/Panada",
    "https://id.wikipedia.org/wiki/Wajik",
    "https://id.wikipedia.org/wiki/Ayam_Rica-Rica",
    "https://id.wikipedia.org/wiki/Mi_cakalang",
    "https://id.wikipedia.org/wiki/Roa",
    "https://id.wikipedia.org/wiki/RW",
    "https://id.wikipedia.org/wiki/Tinutuan",
    "https://id.wikipedia.org/wiki/Tinorangsak",
}

sulawesi_tenggara_urls = {
     "https://id.wikipedia.org/wiki/Kabuto",
    "https://id.wikipedia.org/wiki/Lapa-lapa",
    "https://id.wikipedia.org/wiki/Susuru",
    "https://id.wikipedia.org/wiki/Sinonggi",
    "https://id.wikipedia.org/wiki/Tolaki",
    "https://id.wikipedia.org/wiki/Soami",
}

sulawesi_tengah_urls = {
    "https://id.wikipedia.org/wiki/Apam_paranggi",
    "https://id.wikipedia.org/wiki/Mandura",
    "https://id.wikipedia.org/wiki/Serabi",
    "https://id.wikipedia.org/wiki/Kaledo",
    "https://id.wikipedia.org/wiki/Palumara",
    "https://id.wikipedia.org/wiki/Inuyu",
    "https://id.wikipedia.org/wiki/Kapurung",
    "https://id.wikipedia.org/wiki/Onyop",
    "https://id.wikipedia.org/wiki/Tombouat",
}

sulawesi_barat_urls = {
    "https://id.wikipedia.org/wiki/Kue_Paso",
    "https://id.wikipedia.org/wiki/Apam",
    "https://id.wikipedia.org/wiki/Pukis",
    "https://id.wikipedia.org/wiki/Apam_paranggi",
    "https://id.wikipedia.org/wiki/Jepa",
    "https://id.wikipedia.org/wiki/Bau_peapi",
    "https://id.wikipedia.org/wiki/Loka_anjoroi",
}

maluku_urls = {
    "https://id.wikipedia.org/wiki/Colo-colo",
    "https://id.wikipedia.org/wiki/Papeda",
    "https://id.wikipedia.org/wiki/Nasi_Lapola",
    "https://id.wikipedia.org/wiki/Sambal_Pepaya",
    "https://id.wikipedia.org/wiki/Ikan_asap",
    "https://id.wikipedia.org/wiki/Bagea",
    "https://id.wikipedia.org/wiki/Kasbi",
    "https://id.wikipedia.org/wiki/Lat",
    "https://id.wikipedia.org/wiki/Bubur_sagu_Ambon",
    "https://id.wikipedia.org/wiki/Bubur_Ne",
    "https://id.wikipedia.org/wiki/Gogos",
    "https://id.wikipedia.org/wiki/Kue_asida",
}

maluku_utara_urls = {
    "https://id.wikipedia.org/wiki/Gatang_kenari",
    "https://id.wikipedia.org/wiki/Gohu_ikan",
    "https://id.wikipedia.org/wiki/Kasbi",
    "https://id.wikipedia.org/wiki/Kohu-kohu",
    "https://id.wikipedia.org/wiki/Ula-ula",
    "https://id.wikipedia.org/wiki/Anuve_Habre",
    "https://id.wikipedia.org/wiki/Aunu_Senebre",
    "https://id.wikipedia.org/wiki/Eurimoo",
    "https://id.wikipedia.org/wiki/Sate_ulat_sagu",
    "https://id.wikipedia.org/wiki/Nasi_Goreng_Jawa",
    "https://id.wikipedia.org/wiki/Nasi_Langgi",
    "https://id.wikipedia.org/wiki/Nasi_Kuning",
    "https://id.wikipedia.org/wiki/Panada",
    "https://id.wikipedia.org/wiki/Pukis",
    "https://id.wikipedia.org/wiki/Bika_Ambon",
}

papua_urls = {
    "https://id.wikipedia.org/wiki/Sate_ulat_sagu",
    "https://id.wikipedia.org/wiki/Aunu_Senebre",
    "https://id.wikipedia.org/wiki/Eurimoo",
    "https://id.wikipedia.org/wiki/Anuve_Habre",
}

papua_barat_urls = {
}

province_food_urls = {
    # "ACEH" : aceh_urls,
    # "SUMATERA UTARA" : sumatera_utara_urls,
    # "SUMATERA BARAT" : sumatera_barat_urls,
    # "RIAU" : riau_place_urls,
    # "KEPULAUAN RIAU" : kepulauan_riau_urls,
    # "JAMBI" : jambi_urls,
    # "SUMATERA SELATAN" : sumatera_selatan_urls,
    # "LAMPUNG" : lampung_urls,
    # "BENGKULU" : bengkulu_urls,
    # "BANGKA BELITUNG" : bangka_belitung_urls,
    # "GORONTALO" : gorontalo_urls,
    # "DKI JAKARTA" : dki_jakarta_urls,
    # "JAWA BARAT" : jawa_barat_urls,
    # "BANTEN" : banten_urls,
    # "JAWA TENGAH" : jawa_tengah_urls,
    # "DI YOGYAKARTA" : yogyakarta_urls,
    # "JAWA TIMUR" : jawa_timur_urls,
    # "BALI" : bali_urls,
    # "NUSA TENGGARA BARAT" : nusa_tenggara_barat_urls,
    # "NUSA TENGGARA TIMUR" : nusa_tenggara_timur_urls,
    # "KALIMANTAN BARAT" : kalimantan_barat_urls,
    # "KALIMANTAN SELATAN" : kalimantan_selatan_urls,
    # "KALIMANTAN TENGAH" : kalimantan_tengah_urls,
    # "KALIMANTAN TIMUR" : kalimantan_timur_urls,
    # "KALIMANTAN UTARA" : kalimantan_utara_urls,
    # "SULAWESI SELATAN" : sulawesi_selatan_urls,
    # "SULAWESI UTARA" : sulawesi_utara_urls,
    # "SULAWESI TENGGARA" : sulawesi_tenggara_urls,
    # "SULAWESI TENGAH" : sulawesi_tengah_urls,
    # "SULAWESI BARAT" : sulawesi_barat_urls,
    # "MALUKU" : maluku_urls,
    # "MALUKU UTARA" : maluku_utara_urls,
    "PAPUA" : papua_urls,
    "PAPUA BARAT" : papua_barat_urls,
}
