aceh_urls = [
    "https://id.wikipedia.org/wiki/Masjid_Baiturrahman_Banda_Aceh",
    "https://id.wikipedia.org/wiki/Museum_Tsunami_Aceh",
    "https://id.wikipedia.org/wiki/Museum_Aceh",
    "https://id.wikipedia.org/wiki/Masjid_Baiturrahim_Ulee_Lheue",
    "https://id.wikipedia.org/wiki/Gunung_Seulawah_Agam",
    "https://id.wikipedia.org/wiki/Masjid_Tua_Indra_Puri",
    "https://id.wikipedia.org/wiki/Pulau_Weh",
    "https://id.wikipedia.org/wiki/Tangse,_Pidie",
    "https://id.wikipedia.org/wiki/Meulaboh",
    "https://id.wikipedia.org/wiki/Taman_Nasional_Gunung_Leuser",
    "https://id.wikipedia.org/wiki/Tapak_Tuan,_Aceh_Selatan",
    "https://id.wikipedia.org/wiki/Pulau_Banyak,_Aceh_Singkil"
]

sumatera_utara_urls = [
    "https://id.wikipedia.org/wiki/Istana_Maimun",
    "https://id.wikipedia.org/wiki/Masjid_Raya_Al-Mashun",
    "https://id.wikipedia.org/wiki/Menara_Air_Tirtanadi",
    "https://id.wikipedia.org/wiki/Kantor_Pos_Medan",
    "https://id.wikipedia.org/wiki/Taman_Nasional_Gunung_Leuser",
    "https://id.wikipedia.org/wiki/Sidikalang,_Dairi",
    "https://id.wikipedia.org/wiki/Taman_Wisata_Iman_Dairi",
    "https://id.wikipedia.org/wiki/Museum_Deli_Serdang",
    "https://id.wikipedia.org/wiki/Lubuk_Pakam,_Deli_Serdang",
    "https://id.wikipedia.org/wiki/Gundaling",
    "https://id.wikipedia.org/wiki/Gunung_Sinabung",
    "https://id.wikipedia.org/wiki/Gunung_Sibayak",
    "https://id.wikipedia.org/wiki/Pulau_Kampai,_Pangkalan_Susu,_Langkat",
    "https://id.wikipedia.org/wiki/Bukit_Lawang",
    "https://id.wikipedia.org/wiki/Masjid_Azizi",
    "https://id.wikipedia.org/wiki/Timuran,_Banjarsari,_Surakarta",
    "https://id.wikipedia.org/wiki/Danau_Toba",
    "https://id.wikipedia.org/wiki/Pulau_Samosir",
    "https://id.wikipedia.org/wiki/Museum_Pusaka_Nias"
]

sumatera_barat_urls = [
    "https://id.wikipedia.org/wiki/Jembatan_Sitti_Nurbaya",
    "https://id.wikipedia.org/wiki/Museum_Adityawarman",
    "https://id.wikipedia.org/wiki/Pantai_Carolina",
    "https://id.wikipedia.org/wiki/Pantai_Gandoriah",
    "https://id.wikipedia.org/wiki/Pantai_Padang",
    "https://id.wikipedia.org/wiki/Pulau_Pasumpahan",
    "https://id.wikipedia.org/wiki/Pulau_Sikuai",
    "https://id.wikipedia.org/wiki/Taman_Hutan_Raya_Bung_Hatta",
    "https://id.wikipedia.org/wiki/Taman_Sitti_Nurbaya",
    "https://id.wikipedia.org/wiki/Benteng",
    "https://id.wikipedia.org/wiki/Bukit_Takuruang",
    "https://id.wikipedia.org/wiki/Istana_Bung_Hatta",
    "https://id.wikipedia.org/wiki/Jam_Gadang",
    "https://id.wikipedia.org/wiki/Jembatan_Limpapeh",
    "https://id.wikipedia.org/wiki/Masjid_Jamik_Parabek",
    "https://id.wikipedia.org/wiki/Masjid_Jamik_Taluak_Bukittinggi",
    "https://id.wikipedia.org/wiki/Museum_Rumah_Kelahiran_Bung_Hatta",
    "https://id.wikipedia.org/wiki/Museum_Perjuangan_Tridaya_Eka_Dharma",
    "https://id.wikipedia.org/wiki/Ngarai_Sianok",
    "https://id.wikipedia.org/wiki/Lubang_Jepang_Bukittinggi",
    "https://id.wikipedia.org/wiki/Taman_Margasatwa_dan_Budaya_Kinantan",
    "https://id.wikipedia.org/wiki/Tugu_Pahlawan_Tak_Dikenal",
    "https://id.wikipedia.org/wiki/Danau_Maninjau",
    "https://id.wikipedia.org/wiki/Danau_Tarusan_Kamang",
    "https://id.wikipedia.org/wiki/Kelok_44",
    "https://id.wikipedia.org/wiki/Museum_Kelahiran_Buya_Hamka",
    "https://id.wikipedia.org/wiki/Puncak_Lawang",
    "https://id.wikipedia.org/wiki/Lembah_Harau",
    "https://id.wikipedia.org/wiki/Kelok_9",
    "https://id.wikipedia.org/wiki/Batu_Batikam",
    "https://id.wikipedia.org/wiki/Benteng_Van_der_Capellen",
    "https://id.wikipedia.org/wiki/Istana_Basa_Pagaruyung",
    "https://id.wikipedia.org/wiki/Air_Terjun_Lembah_Anai",
    "https://id.wikipedia.org/wiki/Taman_Nasional_Kerinci_Seblat",
    "https://id.wikipedia.org/wiki/Danau_Singkarak",
    "https://id.wikipedia.org/wiki/Taman_Nasional_Kerinci_Seblat",
    "https://id.wikipedia.org/wiki/Painan,_IV_Jurai,_Pesisir_Selatan",
    "https://id.wikipedia.org/wiki/Pulau_Cubadak",
    "https://id.wikipedia.org/wiki/Pulau_Batunago",
    "https://id.wikipedia.org/wiki/Gedung_Pusat_Kebudayaan_Sawahlunto",
    "https://id.wikipedia.org/wiki/Museum_Situs_Lubang_Tambang_Mbah_Soero",
]

riau_place_urls = {
    "https://id.wikipedia.org/wiki/Cagar_Biosfer_Giam_Siak_Kecil-Bukit_Batu",
    "https://id.wikipedia.org/wiki/Taman_Nasional_Tesso_Nilo",
    "https://id.wikipedia.org/wiki/Masjid_Jami_Air_Tiris",
    "https://id.wikipedia.org/wiki/Candi_Muara_Takus",
    "https://id.wikipedia.org/wiki/Pacu_Jalur",
    "https://id.wikipedia.org/wiki/Taman_Nasional_Tesso_Nilo",
    "https://id.wikipedia.org/wiki/Benteng_Tujuh_Lapis",
    "https://id.wikipedia.org/wiki/Istana_Siak_Sri_Indrapura",
    "https://id.wikipedia.org/wiki/Cagar_Biosfer_Giam_Siak_Kecil-Bukit_Batu",
}

kepulauan_riau_urls = {
    "https://id.wikipedia.org/wiki/Pulau_Bintan",
    "https://id.wikipedia.org/wiki/Gunung_Bintan",
    "https://id.wikipedia.org/wiki/Gunung_Ranai",
}

jambi_urls = {
    "https://id.wikipedia.org/wiki/Candi_Solok_Sipin",
    "https://id.wikipedia.org/wiki/Danau_Sipin",
    "https://id.wikipedia.org/wiki/Masjid_Agung_Al-Falah",
    "https://id.wikipedia.org/wiki/Museum_Perjuangan_Rakyat_Jambi",
    "https://id.wikipedia.org/wiki/Tugu_Keris_Siginjai",
    "https://id.wikipedia.org/wiki/Masjid_Agung_Pondok_Tinggi",
    "https://id.wikipedia.org/wiki/Taman_Nasional_Kerinci_Seblat",
    "https://id.wikipedia.org/wiki/Batang_Hari",
    "https://id.wikipedia.org/wiki/Batang_Tembesi",
    "https://id.wikipedia.org/wiki/Danau_Kerinci",
    "https://id.wikipedia.org/wiki/Taman_Nasional_Kerinci_Seblat",
    "https://id.wikipedia.org/wiki/Gunung_Kerinci",
    "https://id.wikipedia.org/wiki/Kebun_Teh_Kayu_Aro",
    "https://id.wikipedia.org/wiki/Danau_Kaco",
    "https://id.wikipedia.org/wiki/Air_Terjun_Telun_Berasap",
    "https://id.wikipedia.org/wiki/Danau_Gunung_Tujuh",
    "https://id.wikipedia.org/wiki/Air_Terjun_Sigerincing",
    "https://id.wikipedia.org/wiki/Air_Terjun_Muara_Karing",
    "https://id.wikipedia.org/wiki/Air_Terjun_Serintik_Hujan_Paneh",
    "https://id.wikipedia.org/wiki/Air_Terjun_Lematang_Jangkat",
    "https://id.wikipedia.org/wiki/Arung_jeram",
    "https://id.wikipedia.org/wiki/Danau_Pauh",
    "https://id.wikipedia.org/wiki/Gunung_Masurai",
    "https://id.wikipedia.org/wiki/Gunung_Sumbing_(Jambi)",
    "https://id.wikipedia.org/wiki/Jam_Gento",
    "https://id.wikipedia.org/wiki/Taman_Bunga_Merangin_Garden",
    "https://id.wikipedia.org/wiki/Telaga_Biru_Jangkat",
    "https://id.wikipedia.org/wiki/Tugu_Pedang",
    "https://id.wikipedia.org/wiki/Kompleks_Candi_Muaro_Jambi",
    "https://id.wikipedia.org/wiki/Taman_Nasional_Berbak",
    "https://id.wikipedia.org/wiki/Taman_Nasional_Bukit_Tiga_Puluh"
}

sumatera_selatan_urls = {
    "https://id.wikipedia.org/wiki/Gunung_Dempo",
    "https://id.wikipedia.org/wiki/Taman_Nasional_Kerinci_Seblat",
    "https://id.wikipedia.org/wiki/Danau_Ranau",
    "https://id.wikipedia.org/wiki/Jembatan_Ampera",
    "https://id.wikipedia.org/wiki/Masjid_Agung_Palembang",
    "https://id.wikipedia.org/wiki/Sungai_Musi"
}

lampung_urls = {
    "https://id.wikipedia.org/wiki/Taman_Nasional_Bukit_Barisan_Selatan",
    "https://id.wikipedia.org/wiki/Danau_Ranau",
    "https://id.wikipedia.org/wiki/Krakatau",
    "https://id.wikipedia.org/wiki/Menara_Siger",
    "https://id.wikipedia.org/wiki/Kalianda,_Lampung_Selatan",
    "https://id.wikipedia.org/wiki/Teluk_Kiluan",
    "https://id.wikipedia.org/wiki/Taman_Nasional_Bukit_Barisan_Selatan"
}

bengkulu_urls = {
    "https://id.wikipedia.org/wiki/Taman_Nasional_Kerinci_Seblat",
    "https://id.wikipedia.org/wiki/Rumah_Pengasingan_Bung_Karno",
    "https://id.wikipedia.org/wiki/Pantai_Panjang",
    "https://id.wikipedia.org/wiki/Benteng_Marlborough"
}

bangka_belitung_urls = {
    "https://id.wikipedia.org/wiki/Pantai_Parai_Tenggiri",
    "https://id.wikipedia.org/wiki/Pantai_Matras",
    "https://id.wikipedia.org/wiki/Pantai_Tanjung_Pesona",
    "https://id.wikipedia.org/wiki/Gunung_Maras",
    "https://id.wikipedia.org/wiki/Pantai_Tanjung_Kelayang",
    "https://id.wikipedia.org/wiki/Pulau_Lengkuas",
    "https://id.wikipedia.org/wiki/Rumah_Pengasingan_Bung_Karno",
    "https://id.wikipedia.org/wiki/Pulau_Ketawai",
    "https://id.wikipedia.org/wiki/Pantai_Pasir_Padi",
}

gorontalo_urls = {
    "https://id.wikipedia.org/wiki/Benteng_Otanaha",
    "https://id.wikipedia.org/wiki/Pulau_Saronde",
    "https://id.wikipedia.org/wiki/Suaka_Margasatwa_Nantu",
}

dki_jakarta_urls = {
    "https://id.wikipedia.org/wiki/Pulau_Bira",
    "https://id.wikipedia.org/wiki/Pulau_Tidung,_Kepulauan_Seribu_Selatan,_Kepulauan_Seribu",
    "https://id.wikipedia.org/wiki/Pulau_Pramuka",
    "https://id.wikipedia.org/wiki/Museum_Fatahillah",
    "https://id.wikipedia.org/wiki/Museum_Wayang",
    "https://id.wikipedia.org/wiki/Museum_Seni_Rupa_dan_Keramik",
    "https://id.wikipedia.org/wiki/Museum_Tekstil",
    "https://id.wikipedia.org/wiki/Museum_Mandiri",
    "https://id.wikipedia.org/wiki/Pecinan",
    "https://id.wikipedia.org/wiki/Mal_Taman_Anggrek",
    "https://id.wikipedia.org/wiki/Kebayoran_Baru,_Jakarta_Selatan",
    "https://id.wikipedia.org/wiki/Museum_Satria_Mandala",
    "https://id.wikipedia.org/wiki/Blok_M_Plaza",
    "https://id.wikipedia.org/wiki/Plaza_Semanggi",
    "https://id.wikipedia.org/wiki/Pacific_Place",
    "https://id.wikipedia.org/wiki/Mal_Pondok_Indah",
    "https://id.wikipedia.org/wiki/Museum_Timor_Timur",
    "https://id.wikipedia.org/wiki/Pusat_Grosir_Cililitan",
    "https://id.wikipedia.org/wiki/Cibubur_Junction",
    "https://id.wikipedia.org/wiki/Lippo_Plaza_Kramat_Jati",
    "https://id.wikipedia.org/wiki/Museum_Bahari",
    "https://id.wikipedia.org/wiki/Taman_Impian_Jaya_Ancol",
    "https://id.wikipedia.org/wiki/Marina_Beach",
    "https://id.wikipedia.org/wiki/Bartega",
    "https://id.wikipedia.org/wiki/Mall_of_Indonesia",
    "https://id.wikipedia.org/wiki/Mangga_Dua_Square",
    "https://id.wikipedia.org/wiki/WTC_Mangga_Dua",
    "https://id.wikipedia.org/wiki/Taman_Ayodya",
    "https://id.wikipedia.org/wiki/Taman_Safari_Indonesia",
    "https://id.wikipedia.org/wiki/Taman_Margasatwa_Ragunan",
    "https://id.wikipedia.org/wiki/Setu_Babakan",
    "https://id.wikipedia.org/wiki/Suku_Betawi",
    "https://id.wikipedia.org/wiki/Plaza_Indonesia",
    "https://id.wikipedia.org/wiki/FX_Sudirman",
    "https://id.wikipedia.org/wiki/Senayan_City",
    "https://id.wikipedia.org/wiki/Gedung_Sarinah",
    "https://id.wikipedia.org/wiki/Grand_Indonesia",
    "https://id.wikipedia.org/wiki/Museum_Bank_Indonesia",
    "https://id.wikipedia.org/wiki/Planetarium",
    "https://id.wikipedia.org/wiki/Gedung_Joang_%2745",
    "https://id.wikipedia.org/wiki/Museum_Taman_Prasasti",
    "https://id.wikipedia.org/wiki/Museum_Nasional_Indonesia",
    "https://id.wikipedia.org/wiki/Monumen_Nasional",
    "https://id.wikipedia.org/wiki/Gedung_Mohammad_Hoesni_Thamrin",
    "https://id.wikipedia.org/wiki/Museum_Taman_Prasasti",
    "https://id.wikipedia.org/wiki/Museum_Sumpah_Pemuda",
    "https://id.wikipedia.org/wiki/Kota_Tua_Jakarta",
    "https://id.wikipedia.org/wiki/Taman_Ismail_Marzuki",
    "https://id.wikipedia.org/wiki/Taman_Menteng",
    "https://id.wikipedia.org/wiki/Sawah_Besar,_Jakarta_Pusat",
    "https://id.wikipedia.org/wiki/Pasar_Baru",
    "https://id.wikipedia.org/wiki/Masjid_Istiqlal,_Jakarta",
    "https://id.wikipedia.org/wiki/Tugu_Proklamasi",
    "https://id.wikipedia.org/wiki/Mal_Ciputra_Jakarta",
    "https://id.wikipedia.org/wiki/Mal_Puri_Indah",
}

jawa_barat_urls = {
    "https://id.wikipedia.org/wiki/Gedung_Sate",
    "https://id.wikipedia.org/wiki/Museum_Konferensi_Asia_Afrika",
    "https://id.wikipedia.org/wiki/Taman_Hutan_Raya_Ir._H._Djuanda",
    "https://id.wikipedia.org/wiki/Tebing_Keraton",
    "https://id.wikipedia.org/wiki/Trans_Studio_Bandung",
    "https://id.wikipedia.org/wiki/Paris_Van_Java_Mall",
    "https://id.wikipedia.org/wiki/Museum_Geologi_Bandung",
    "https://id.wikipedia.org/wiki/Alun-alun_Bandung",
    "https://id.wikipedia.org/wiki/Saung_Angklung_Udjo",
    "https://id.wikipedia.org/wiki/Curug_Cimahi",
    "https://id.wikipedia.org/wiki/Keraton_Kasepuhan",
    "https://id.wikipedia.org/wiki/Keraton_Kacirebonan",
    "https://id.wikipedia.org/wiki/Masjid_Agung_Cirebon",
    "https://id.wikipedia.org/wiki/Masjid_Sumber",
    "https://id.wikipedia.org/wiki/Taman_Sari_Gua_Sunyaragi",
    "https://id.wikipedia.org/wiki/Bendungan_Rentang",
    "https://id.wikipedia.org/wiki/Taman_Nasional_Gunung_Ciremai",
    "https://id.wikipedia.org/wiki/Situ_Janawi",
    "https://id.wikipedia.org/wiki/Taman_Nasional_Gunung_Gede_Pangrango",
    "https://id.wikipedia.org/wiki/Taman_Safari_Indonesia",
    "https://id.wikipedia.org/wiki/Telaga_Warna_(Puncak,_Bogor)",
    "https://id.wikipedia.org/wiki/Curug_Panjang",
    "https://id.wikipedia.org/wiki/Curug_Cibeureum",
    "https://id.wikipedia.org/wiki/Curug_Ciherang",
    "https://id.wikipedia.org/wiki/Taman_Nasional_Gunung_Gede_Pangrango",
    "https://id.wikipedia.org/wiki/Keraton_Kasepuhan",
    "https://id.wikipedia.org/wiki/Setu_Patok",
    "https://id.wikipedia.org/wiki/Istana_Bogor",
    "https://id.wikipedia.org/wiki/Kebun_Raya_Bogor",
    "https://id.wikipedia.org/wiki/Masjid_Dian_Al-Mahri",
}

banten_urls = {
    "https://id.wikipedia.org/wiki/Taman_Nasional_Ujung_Kulon",
    "https://id.wikipedia.org/wiki/Anyar,_Serang",
}

jawa_tengah_urls = {
    "https://id.wikipedia.org/wiki/Lawang_Sewu",
    "https://id.wikipedia.org/wiki/Taman_Budaya_Raden_Saleh",
    "https://id.wikipedia.org/wiki/Puri_Maerokoco",
    "https://id.wikipedia.org/wiki/Masjid_Agung_Jawa_Tengah",
    "https://id.wikipedia.org/wiki/Rawa_Pening",
    "https://id.wikipedia.org/wiki/Candi_Gedong_Songo",
    "https://id.wikipedia.org/wiki/Museum_Kereta_Api_Ambarawa",
    "https://id.wikipedia.org/wiki/Kepulauan_Karimunjawa",
    "https://id.wikipedia.org/wiki/Pulau_Panjang_(Jawa_Tengah)",
    "https://id.wikipedia.org/wiki/Pantai_Kartini",
    "https://id.wikipedia.org/wiki/Air_Terjun_Songgo_Langit",
    "https://id.wikipedia.org/wiki/Goa_Sakti",
    "https://id.wikipedia.org/wiki/Benteng_Portugis_(Jepara)",
    "https://id.wikipedia.org/wiki/Benteng_VOC_(Jepara)",
    "https://id.wikipedia.org/wiki/Museum_Kartini",
    "https://id.wikipedia.org/wiki/Masjid_Baiturrahman_1_Robayan",
    "https://id.wikipedia.org/wiki/Siti_Inggil_Kriyan",
    "https://id.wikipedia.org/wiki/Kura-Kura_Ocean_Park",
    "https://id.wikipedia.org/wiki/Shopping_Centre_Jepara",
    "https://id.wikipedia.org/wiki/Masjid_Menara_Kudus",
    "https://id.wikipedia.org/wiki/Air_Terjun_Monthel",
    "https://id.wikipedia.org/wiki/Masjid_Agung_Demak",
    "https://id.wikipedia.org/wiki/Telaga_Menjer",
    "https://id.wikipedia.org/wiki/Telaga_Warna_(Dieng)",
    "https://id.wikipedia.org/wiki/Air_terjun_Sikarim",
    "https://id.wikipedia.org/wiki/Bledug_Kuwu",
    "https://id.wikipedia.org/wiki/Pantai_Widuri",
    "https://id.wikipedia.org/wiki/Waduk_Malahayu",
    "https://id.wikipedia.org/wiki/Waduk_Penjalin",
    "https://id.wikipedia.org/wiki/Borobudur",
    "https://id.wikipedia.org/wiki/Candi_Mendut",
    "https://id.wikipedia.org/wiki/Ketep_Pass",
    "https://id.wikipedia.org/wiki/Candi_Ngawen",
    "https://id.wikipedia.org/wiki/Curug_Silawe",
    "https://id.wikipedia.org/wiki/Waduk_Sempor",
    "https://id.wikipedia.org/wiki/Curug_Cipendok",
    "https://id.wikipedia.org/wiki/Museum_Bank_Rakyat_Indonesia",
    "https://id.wikipedia.org/wiki/Masjid_Saka_Tunggal_Banyumas",
    "https://id.wikipedia.org/wiki/Benteng_Willem_II",
    "https://id.wikipedia.org/wiki/Pegunungan_Dieng",
    "https://id.wikipedia.org/wiki/Grojogan_Sewu",
    "https://id.wikipedia.org/wiki/Candi_Sukuh",
    "https://id.wikipedia.org/wiki/Candi_Ceto",
    "https://id.wikipedia.org/wiki/Astana_Giribangun",
    "https://id.wikipedia.org/wiki/Candi_Sewu",
    "https://id.wikipedia.org/wiki/Candi_Plaosan",
    "https://id.wikipedia.org/wiki/Rowo_Jombor",
    "https://id.wikipedia.org/wiki/Waduk_Gajah_Mungkur",
    "https://id.wikipedia.org/wiki/Museum_Radya_Pustaka",
    "https://id.wikipedia.org/wiki/Taman_Balekambang",
    "https://id.wikipedia.org/wiki/Pasar_Klewer",
    "https://id.wikipedia.org/wiki/Pasar_Gede_Harjonagoro",
    "https://id.wikipedia.org/wiki/Benteng_Vastenburg",
    "https://id.wikipedia.org/wiki/Taman_Sriwedari",
    "https://id.wikipedia.org/wiki/Museum_Batik_Danar_Hadi",
    "https://id.wikipedia.org/wiki/Pantai_Teluk_Awur",
    "https://id.wikipedia.org/wiki/Pantai_Pailus",
}

yogyakarta_urls = {
    "https://id.wikipedia.org/wiki/Alun-alun",
    "https://id.wikipedia.org/wiki/Keraton_Ngayogyakarta_Hadiningrat",
    "https://id.wikipedia.org/wiki/Taman_Sari_Yogyakarta",
    "https://id.wikipedia.org/wiki/Situs_Warungboto",
    "https://id.wikipedia.org/wiki/Pura_Pakualaman",
    "https://id.wikipedia.org/wiki/Taman_Pintar_Yogyakarta",
    "https://id.wikipedia.org/wiki/Kotagede,_Yogyakarta",
    "https://id.wikipedia.org/wiki/Kebun_Binatang_Gembira_Loka",
    "https://id.wikipedia.org/wiki/Jalan_Malioboro",
    "https://id.wikipedia.org/wiki/Tugu_Yogyakarta",
    "https://id.wikipedia.org/wiki/Pasar_Beringharjo",
    "https://id.wikipedia.org/wiki/Benteng_Vred%D0%B5burg",
    "https://id.wikipedia.org/wiki/Titik_Nol_Kilometer_Yogyakarta",
    "https://id.wikipedia.org/wiki/Candi_Prambanan",
    "https://id.wikipedia.org/wiki/Situs_Ratu_Baka",
    "https://id.wikipedia.org/wiki/Candi_Ijo",
    "https://id.wikipedia.org/wiki/Candi_Sambisari",
    "https://id.wikipedia.org/wiki/Candi_Sari",
    "https://id.wikipedia.org/wiki/Candi_Barong",
    "https://id.wikipedia.org/wiki/Candi_Kalasan",
    "https://id.wikipedia.org/wiki/Candi_Banyunibo",
    "https://id.wikipedia.org/wiki/Tebing_Breksi",
    "https://id.wikipedia.org/wiki/Museum_Affandi",
    "https://id.wikipedia.org/wiki/Kaliurang",
    "https://id.wikipedia.org/wiki/Kaliadem",
    "https://id.wikipedia.org/wiki/Bukit_Klangon",
    "https://id.wikipedia.org/wiki/Gunung_Merapi",
    "https://id.wikipedia.org/wiki/Merapi_Park",
    "https://id.wikipedia.org/wiki/The_Lost_World_Castle",
    "https://id.wikipedia.org/wiki/Pantai_Baron",
    "https://id.wikipedia.org/wiki/Pantai_Drini",
    "https://id.wikipedia.org/wiki/Pantai_Siung",
    "https://id.wikipedia.org/wiki/Pantai_Timang",
    "https://id.wikipedia.org/wiki/Pantai_Nguyahan",
    "https://id.wikipedia.org/wiki/Pantai_Ngobaran",
    "https://id.wikipedia.org/wiki/Air_Terjun_Sri_Gethuk",
    "https://id.wikipedia.org/wiki/Gua_Pindul",
    "https://id.wikipedia.org/wiki/Gua_Jomblang",
    "https://id.wikipedia.org/wiki/Embung_Nglanggeran",
    "https://id.wikipedia.org/wiki/Bukit_Bintang",
    "https://id.wikipedia.org/wiki/Pantai_Parangtritis",
    "https://id.wikipedia.org/wiki/Pantai_Parangkusumo",
    "https://id.wikipedia.org/wiki/Pantai_Baru",
    "https://id.wikipedia.org/wiki/Gumuk_Pasir_Parangkusumo",
    "https://id.wikipedia.org/wiki/Gardu_Pandang_Lemah_Rubuh",
    "https://id.wikipedia.org/wiki/Curug_Pulosari",
    "https://id.wikipedia.org/wiki/Gua_Selarong",
    "https://id.wikipedia.org/wiki/Mangunan,_Dlingo,_Bantul",
    "https://id.wikipedia.org/wiki/Kasongan",
    "https://id.wikipedia.org/wiki/Hutan_Pinus_Mangunan",
    "https://id.wikipedia.org/wiki/Hutan_Pinus_Pengger",
    "https://id.wikipedia.org/wiki/Puncak_Becici",
    "https://id.wikipedia.org/wiki/Bukit_Bego",
    "https://id.wikipedia.org/wiki/History_of_Java_Museum",
    "https://id.wikipedia.org/wiki/Museum_Wayang_Kekayon",
    "https://id.wikipedia.org/wiki/Museum_Pleret",
    "https://id.wikipedia.org/wiki/Pantai_Glagah_Indah",
    "https://id.wikipedia.org/wiki/Air_Terjun_Kedung_Pedut",
    "https://id.wikipedia.org/wiki/Waduk_Sermo",
    "https://id.wikipedia.org/wiki/Puncak_Suroloyo",
    "https://id.wikipedia.org/wiki/Danau_Kalibiru",
}

jawa_timur_urls = {
    "https://id.wikipedia.org/wiki/Kota_Surabaya",
    "https://id.wikipedia.org/wiki/Jembatan_Nasional_Suramadu",
    "https://id.wikipedia.org/wiki/Kota_Malang",
    "https://id.wikipedia.org/wiki/Taman_Nasional_Bromo_Tengger_Semeru",
    "https://id.wikipedia.org/wiki/Pulau_Sempu",
    "https://id.wikipedia.org/wiki/Pantai_Balekambang",
    "https://id.wikipedia.org/wiki/Pantai_Ngliyep",
    "https://id.wikipedia.org/wiki/Batu_Secret_Zoo",
    "https://id.wikipedia.org/wiki/Museum_Satwa",
    "https://id.wikipedia.org/wiki/Jatim_Park",
    "https://id.wikipedia.org/wiki/Asta_Tinggi_Sumenep",
    "https://id.wikipedia.org/wiki/Keraton_Sumenep",
    "https://id.wikipedia.org/wiki/Jembatan_Nasional_Suramadu",
    "https://id.wikipedia.org/wiki/Pantai_Prigi",
    "https://id.wikipedia.org/wiki/Pantai_Serang",
    "https://id.wikipedia.org/wiki/Gunung_Kelud",
    "https://id.wikipedia.org/wiki/Pantai_Tambakrejo",
    "https://id.wikipedia.org/wiki/Candi_Sawentar",
    "https://id.wikipedia.org/wiki/Candi_Plumbangan",
    "https://id.wikipedia.org/wiki/Pantai_Jolosutro",
    "https://id.wikipedia.org/wiki/Gunung_Ijen",
    "https://id.wikipedia.org/wiki/Watu_Dodol",
    "https://id.wikipedia.org/wiki/Blimbingsari,_Blimbingsari,_Banyuwangi",
    "https://id.wikipedia.org/wiki/Pantai_Rajegwesi",
    "https://id.wikipedia.org/wiki/Gunung_Bromo",
    "https://id.wikipedia.org/wiki/Gunung_Semeru",
    "https://id.wikipedia.org/wiki/Air_Terjun_Kakek_Bodo",
    "https://id.wikipedia.org/wiki/Telaga_Sarangan",
    "https://id.wikipedia.org/wiki/Air_Terjun_Sedudo",
}

bali_urls = {
    "https://id.wikipedia.org/wiki/Candi_Dasa",
    "https://id.wikipedia.org/wiki/Taman_Budaya_Garuda_Wisnu_Kencana",
    "https://id.wikipedia.org/wiki/Pantai_Kuta",
    "https://id.wikipedia.org/wiki/Pantai_Lovina",
    "https://id.wikipedia.org/wiki/Pantai_Pandawa",
    "https://id.wikipedia.org/wiki/Pantai_Sanur",
    "https://id.wikipedia.org/wiki/Nusa_Penida",
    "https://id.wikipedia.org/wiki/Nusa_Ceningan",
    "https://id.wikipedia.org/wiki/Nusa_Lembongan",
    "https://id.wikipedia.org/wiki/Nusa_Dua",
    "https://id.wikipedia.org/wiki/Tanah_Lot",
    "https://id.wikipedia.org/wiki/Kebun_Raya_Bali",
    "https://id.wikipedia.org/wiki/Tirta_Gangga",
    "https://id.wikipedia.org/wiki/Istana_Tampaksiring",
    "https://id.wikipedia.org/wiki/Taman_Ujung",
    "https://id.wikipedia.org/wiki/Taman_Werdhi_Budaya_Art_Centre",
    "https://id.wikipedia.org/wiki/Danau_Bratan",
    "https://id.wikipedia.org/wiki/Danau_Batur",
    "https://id.wikipedia.org/wiki/Gunung_Agung",
    "https://id.wikipedia.org/wiki/Gunung_Batur",
    "https://id.wikipedia.org/wiki/Paviliun_Kerta_Gosa",
    "https://id.wikipedia.org/wiki/Taman_Nasional_Bali_Barat",
    "https://id.wikipedia.org/wiki/Air_Terjun_Tegenungan",
    "https://id.wikipedia.org/wiki/Bali_Safari_%26_Marine_Park",
    "https://id.wikipedia.org/wiki/Mandala_Wisata_Wenara_Wana",
}

nusa_tenggara_barat_urls = {
    "https://id.wikipedia.org/wiki/Pantai_Senggigi",
    "https://id.wikipedia.org/wiki/Taman_Narmada",
    "https://id.wikipedia.org/wiki/Taman_Mayura",
    "https://id.wikipedia.org/wiki/Gunung_Rinjani",
    "https://id.wikipedia.org/wiki/Pantai_Kuta,_Lombok",
    "https://id.wikipedia.org/wiki/Air_Terjun_Sendang_Gile",
    "https://id.wikipedia.org/wiki/Gunung_Tambora",
    "https://id.wikipedia.org/wiki/Museum_Samparaja",
}

nusa_tenggara_timur_urls = {
    "https://id.wikipedia.org/wiki/Taman_Nasional_Komodo",
    "https://id.wikipedia.org/wiki/Gunung_Kelimutu",
    "https://id.wikipedia.org/wiki/Labuan_Bajo,_Komodo,_Manggarai_Barat",
    "https://id.wikipedia.org/wiki/Taman_Nasional_Manupeu_Tanah_Daru",
    "https://id.wikipedia.org/wiki/Taman_Nasional_Laiwangi_Wanggameti",
    "https://id.wikipedia.org/wiki/Gunung_Mutis",
}

kalimantan_barat_urls = {
    "https://id.wikipedia.org/wiki/Taman_Nasional_Danau_Sentarum",
    "https://id.wikipedia.org/wiki/Taman_Nasional_Betung_Kerihun",
    "https://id.wikipedia.org/wiki/Kepulauan_Karimata",
    "https://id.wikipedia.org/wiki/Taman_Nasional_Gunung_Palung",
    "https://id.wikipedia.org/wiki/Taman_Nasional_Bukit_Baka-Bukit_Raya",
    "https://id.wikipedia.org/wiki/Cagar_Alam_Raya_Pasi",
    "https://id.wikipedia.org/wiki/Museum_Kapuas_Raya",
    "https://id.wikipedia.org/wiki/Gunung_Kelam",
    "https://id.wikipedia.org/wiki/Taman_Nasional_Bukit_Baka-Bukit_Raya",
    "https://id.wikipedia.org/wiki/Sinka_Island_Park",
    "https://id.wikipedia.org/wiki/Pantai_Pasir_Panjang",
    "https://id.wikipedia.org/wiki/Pulau_Simping",
}

kalimantan_selatan_urls = {
    "https://id.wikipedia.org/wiki/Pasar_Terapung_Muara_Kuin",
    "https://id.wikipedia.org/wiki/Pasar_Terapung_Lok_Baintan",
    "https://id.wikipedia.org/wiki/Jembatan_Barito",
    "https://id.wikipedia.org/wiki/Pegunungan_Meratus",
    "https://id.wikipedia.org/wiki/Candi_Agung",
    "https://id.wikipedia.org/wiki/Pantai_Pagatan",
    "https://id.wikipedia.org/wiki/Pantai_Takisung",
    "https://id.wikipedia.org/wiki/Pantai_Batakan",
    "https://id.wikipedia.org/wiki/Pantai_Swarangan",
    "https://id.wikipedia.org/wiki/Museum_Lambung_Mangkurat",
    "https://id.wikipedia.org/wiki/Museum_Waja_Sampai_Ka_Puting",
    "https://id.wikipedia.org/wiki/Masjid_Sultan_Suriansyah",
    "https://id.wikipedia.org/wiki/Sungai_Barito",
    "https://id.wikipedia.org/wiki/Sungai_Kapuas",
    "https://id.wikipedia.org/wiki/Taman_Nasional_Tanjung_Puting",
}

kalimantan_tengah_urls = {
    "https://id.wikipedia.org/wiki/Sungai_Barito",
    "https://id.wikipedia.org/wiki/Sungai_Kapuas",
    "https://id.wikipedia.org/wiki/Taman_Nasional_Bukit_Baka-Bukit_Raya",
    "https://id.wikipedia.org/wiki/Taman_Nasional_Sebangau",
    "https://id.wikipedia.org/wiki/Taman_Nasional_Tanjung_Puting",
}

kalimantan_timur_urls = {
    "https://id.wikipedia.org/wiki/Kepulauan_Derawan",
    "https://id.wikipedia.org/wiki/Kedaton_Kutai_Kartanegara",
    "https://id.wikipedia.org/wiki/Sungai_Mahakam",
    "https://id.wikipedia.org/wiki/Pulau_Derawan",
    "https://id.wikipedia.org/wiki/Pulau_Maratua",
    "https://id.wikipedia.org/wiki/Pulau_Kakaban",
}

kalimantan_utara_urls = {
    "https://id.wikipedia.org/wiki/Taman_Nasional_Kayan_Mentarang",
    "https://id.wikipedia.org/wiki/Pulau_Sebatik     ",
}

sulawesi_selatan_urls = {
    "https://id.wikipedia.org/wiki/Malino,_Tinggimoncong,_Gowa",
    "https://id.wikipedia.org/wiki/Benteng_Somba_Opu",
    "https://id.wikipedia.org/wiki/Agrowisata_Mangambang_575",
    "https://id.wikipedia.org/wiki/Museum_Balla_Lompoa",
    "https://id.wikipedia.org/wiki/Agrowisata_Pucak",
    "https://id.wikipedia.org/wiki/Air_terjun_Bantimurung",
    "https://id.wikipedia.org/wiki/Air_terjun_Lacolla",
    "https://id.wikipedia.org/wiki/Danau_Kassi_Kebo",
    "https://id.wikipedia.org/wiki/Gua_Mimpi",
    "https://id.wikipedia.org/wiki/Leang_Timpuseng",
    "https://id.wikipedia.org/wiki/Grand_Mall_Maros",
    "https://id.wikipedia.org/wiki/Helena_Sky_Bridge",
    "https://id.wikipedia.org/wiki/Pantai_Kuri_Caddi",
    "https://id.wikipedia.org/wiki/Rammang-Rammang",
    "https://id.wikipedia.org/wiki/Taman_Nasional_Bantimurung-Bulusaraung",
    "https://id.wikipedia.org/wiki/Taman_Prasejarah_Leang_Leang",
    "https://id.wikipedia.org/wiki/Kabupaten_Tana_Toraja",
    "https://id.wikipedia.org/wiki/Danau_Tempe",
    "https://id.wikipedia.org/wiki/Pulau_Samalona",
    "https://id.wikipedia.org/wiki/Fort_Rotterdam",
    "https://id.wikipedia.org/wiki/Air_terjun_Bantimurung",
    "https://id.wikipedia.org/wiki/Air_terjun_Jami",
    "https://id.wikipedia.org/wiki/Air_terjun_Lacolla",
    "https://id.wikipedia.org/wiki/Air_terjun_Lengang_Laiya",
    "https://id.wikipedia.org/wiki/Air_terjun_Pung_Bunga",
    "https://id.wikipedia.org/wiki/Air_terjun_Saliu",
    "https://id.wikipedia.org/wiki/Air_terjun_Taipa",
    "https://id.wikipedia.org/wiki/Air_terjun_Tumbu",
}

sulawesi_utara_urls = {
    "https://id.wikipedia.org/wiki/Danau_Tondano",
    "https://id.wikipedia.org/wiki/Taman_Nasional_Bunaken",
    "https://id.wikipedia.org/wiki/Gunung_Mahawu",
    "https://id.wikipedia.org/wiki/Pantai_Indah_Modisi",
}

sulawesi_tenggara_urls = {
    "https://id.wikipedia.org/wiki/Pantai_Nambo",
    "https://id.wikipedia.org/wiki/Puspa_patuk",
    "https://id.wikipedia.org/wiki/Danau_Napabale",
    "https://id.wikipedia.org/wiki/Taman_Nasional_Wakatobi",
    "https://id.wikipedia.org/wiki/Air_Terjun_Moramo",
    "https://id.wikipedia.org/wiki/Benteng_Keraton_Buton",
    "https://id.wikipedia.org/wiki/Istana_Malige",
    "https://id.wikipedia.org/wiki/Pulau_Liwutongkidi",
}

sulawesi_tengah_urls = {
    "https://id.wikipedia.org/wiki/Taman_Nasional_Lore_Lindu",
    "https://id.wikipedia.org/wiki/Danau_Lindu",
    "https://id.wikipedia.org/wiki/Pantai_Tanjung_Karang",
    "https://id.wikipedia.org/wiki/Pantai_Boneoge",
    "https://id.wikipedia.org/wiki/Pusentasi",
    "https://id.wikipedia.org/wiki/Pantai_Kaluku",
    "https://id.wikipedia.org/wiki/Taman_Nasional_Kepulauan_Togean",
    "https://id.wikipedia.org/wiki/Kepulauan_Togean",
    "https://id.wikipedia.org/wiki/Pulau_Kadidiri",
    "https://id.wikipedia.org/wiki/Pulau_Malenge",
    "https://id.wikipedia.org/wiki/Pulau_Una-Una",
    "https://id.wikipedia.org/wiki/Gunung_Colo",
    "https://id.wikipedia.org/wiki/Danau_Poso",
    "https://id.wikipedia.org/wiki/Gua_Latea",
    "https://id.wikipedia.org/wiki/Air_Terjun_Saluopa",
    "https://id.wikipedia.org/wiki/Pantai_Siuri",
    "https://id.wikipedia.org/wiki/Jembatan_Palu_IV",
    "https://id.wikipedia.org/wiki/Kabupaten_Pasangkayu",
}

sulawesi_barat_urls = {
    "https://id.wikipedia.org/wiki/Kabupaten_Mamuju",
    "https://id.wikipedia.org/wiki/Kabupaten_Mamasa",
    "https://id.wikipedia.org/wiki/Kabupaten_Majene",
    "https://id.wikipedia.org/wiki/Kabupaten_Pasangkayu",
}

maluku_urls = {
    "https://id.wikipedia.org/wiki/Maluku",
    "https://id.wikipedia.org/wiki/Banda_Neira",
}

maluku_utara_urls = {
    "https://id.wikipedia.org/wiki/Gunung_Gamalama",
    "https://id.wikipedia.org/wiki/Kota_Ternate",
    "https://id.wikipedia.org/wiki/Danau_Tolire",
    "https://id.wikipedia.org/wiki/Masjid_Raya_Al_Munawwar_Ternate",
    "https://id.wikipedia.org/wiki/Benteng_Kastela",
    "https://id.wikipedia.org/wiki/Benteng_Tolukko",
    "https://id.wikipedia.org/wiki/Baabullah",
    "https://id.wikipedia.org/wiki/Masjid_Sultan_Ternate",
    "https://id.wikipedia.org/wiki/Pulau_Maitara",
    "https://id.wikipedia.org/wiki/Taman_Nasional_Aketajawe-Lolobata",
}

papua_urls = {
    "https://id.wikipedia.org/wiki/Teluk_Cenderawasih",
    "https://id.wikipedia.org/wiki/Taman_Nasional_Lorentz",
    "https://id.wikipedia.org/wiki/Agats,_Asmat",
    "https://id.wikipedia.org/wiki/Puncak_Jaya",
    "https://id.wikipedia.org/wiki/Danau_Sentani",
    "https://id.wikipedia.org/wiki/Lembah_Baliem",
    "https://id.wikipedia.org/wiki/Puncak_Trikora",
    "https://id.wikipedia.org/wiki/Puncak_Mandala",
    "https://id.wikipedia.org/wiki/Barisan_Sudirman",
    "https://id.wikipedia.org/wiki/Taman_Nasional_Wasur",
    "https://id.wikipedia.org/wiki/Danau_Paniai",
    "https://id.wikipedia.org/wiki/Sungai_Mamberamo",
    "https://id.wikipedia.org/wiki/Danau_Sentani",
}

papua_barat_urls = {
    "https://id.wikipedia.org/wiki/Masjid_Tua_Patimburak",
    "https://id.wikipedia.org/wiki/Kabupaten_Kaimana",
    "https://id.wikipedia.org/wiki/Teluk_Triton",
    "https://id.wikipedia.org/wiki/Taman_Nasional_Teluk_Cenderawasih",
    "https://id.wikipedia.org/wiki/Cagar_Alam_Pegunungan_Arfak",
    "https://id.wikipedia.org/wiki/Pulau_Mansinam",
    "https://id.wikipedia.org/wiki/Kepulauan_Raja_Ampat",
    "https://id.wikipedia.org/wiki/Pulau_Waigeo",
    "https://id.wikipedia.org/wiki/Pulau_Misool",
    "https://id.wikipedia.org/wiki/Cenderawasih_kuning-kecil",
    "https://id.wikipedia.org/wiki/Pulau_Salawati",
    "https://id.wikipedia.org/wiki/Taman_Nasional_Teluk_Cenderawasih",
}

category_data = {
    "Masjid": "https://api2.kemenparekraf.go.id/storage/app/uploads/public/624/18c/863/62418c8630fa8490512129.jpg",
    "Museum": "https://media.cntraveler.com/photos/5a7b4d2741ac86020aab80eb/16:9/w_2560,c_limit/Natural-History-Museum_Trustees-of-the-Natural-History-Museum,-London__2018_20170718-Blue-Whale-Hintze-Hall-1-Credit--Trustees-of-NHM.webp",
    "Pulau": "https://www.indonesia.travel/content/dam/indtravelrevamp/en/destinations/revision-2019/all-revision-destination/rajaampatH.jpg",
    "Taman Nasional": "https://i.natgeofe.com/n/c1d2d9ea-061e-4a74-9ed2-6c716d0e3f78/padar-island.jpg",
    "Gunung": "https://cdn.idntimes.com/content-images/community/2017/07/taman-nasional-bromo-tengger-jawa-timur-indonesia1-fec4c7dbdd891361257e3ac013896e6f.jpg",
    "Istana": "https://edensorhills.com/wp-content/uploads/2022/12/Istana-Bogor-Bogor-Palace-1024x576.jpg",
    "Kantor": "https://png.pngtree.com/background/20230604/original/pngtree-modern-corporate-business-office-background-wallpaper-picture-image_2873050.jpg",
    "Danau": "https://img2.beritasatu.com/cache/beritasatu/960x620-3/2023/10/1696833602-2000x1333.webp",
    "Bukit": "https://ik.imagekit.io/tvlk/blog/2021/08/shutterstock_2012584787.jpg?tr=dpr-2,w-675",
    "Pantai": "https://www.indonesia.travel/content/dam/indtravelrevamp/user-generated-content/ugc-july-2020/gb-en/5.jpg",
    "Jam": "https://salsawisata.com/wp-content/uploads/2022/03/Jam-Gadang-Bukittinggi.jpg",
    "Jembatan": "https://img.merahputih.com/media/ef/88/ad/ef88adb75ebeec1defde0076c30e41ea.jpg",
    "Lembah": "https://ksmtour.com/media/images/articles7/lembah-harau-sumatera-barat.jpg",
    "Benteng": "https://www.indonesia.travel/content/dam/indtravelrevamp/id-id/ide-liburan/mau-wisata-unik-diindonesiaaja-intip-6-benteng-dari-era-kolonial-ini-yuk/thumbnail.jpg",
    "Cagar": "https://www.indonesia.travel/content/dam/indtravelrevamp/en/trip-ideas/5-cagar-biosfer-ini-cocok-jadi-destinasi-wisata-edukatif/wakatobi.jpg",
    "Candi": "https://www.indonesia.travel/content/dam/indtravelrevamp/user-generated-content/ugc-july-2020/gb-en/3.jpg",
    "Sungai": "https://awsimages.detik.net.id/community/media/visual/2022/11/18/pola-aliran-sungai_169.jpeg?w=1200",
    "Air Terjun": "https://ik.imagekit.io/tvlk/blog/2023/07/Tibumana-Waterfall.jpg?tr=dpr-2,w-675",
    "Telaga": "https://www.rayadventure.com/wp-content/uploads/2018/06/telaga-sarangan-magetan.jpg",
    "Tugu": "https://asset.kompas.com/crops/ahyz8cGMziGomWaZj-zHbXpP4HA=/178x83:973x613/750x500/data/photo/2021/12/27/61c9b9883a01d.png",
    "Teluk": "https://static.promediateknologi.id/crop/0x0:0x0/750x500/webp/photo/2023/04/02/IMG_20230402_135500-3733925383.jpg",
    "Rumah": "https://static.promediateknologi.id/crop/0x0:0x0/0x0/webp/photo/jawapos/2022/11/dusun-bambu.jpg",
    "Monumen": "https://www.iwarebatik.org/wp-content/uploads/2019/11/monas.jpg",
    "Perbelanjaan": "https://static.promediateknologi.id/crop/0x0:0x0/750x500/webp/photo/p1/77/2023/09/21/wisata-mall-di-semarang-851855348.jpg",
    "Kota Tua Jakarta": "https://asset.kompas.com/crops/t81xct6MASs87SPsIfWbKP_pOlI=/0x0:0x0/750x500/data/photo/2023/04/24/6446975b10016.jpg",
    "Taman": "https://www.itrip.id/wp-content/uploads/2020/05/Tentang-Taman-Bunga-Nusantara.jpg.webp",
    "Gedung": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Jakarta_Skyline_Part_2.jpg/600px-Jakarta_Skyline_Part_2.jpg",
    "Curug": "https://akcdn.detik.net.id/visual/2020/12/16/air-terjun-banyumala_169.jpeg?w=650",
    "Hutan": "https://cdn.idntimes.com/content-images/post/20220714/orchid-forest2-97a8bb935cdb3d018ff75f640ce27ed9.jpg",
    "Kabupaten": "https://upload.wikimedia.org/wikipedia/commons/4/49/Rumah_Adat_Mamuju.jpg"
}

province_place_urls = {
    "ACEH" : aceh_urls,
    "SUMATERA UTARA" : sumatera_utara_urls,
    "SUMATERA BARAT" : sumatera_barat_urls,
    "RIAU" : riau_place_urls,
    "KEPULAUAN RIAU" : kepulauan_riau_urls,
    "JAMBI" : jambi_urls,
    "SUMATERA SELATAN" : sumatera_selatan_urls,
    "LAMPUNG" : lampung_urls,
    "BENGKULU" : bengkulu_urls,
    "BANGKA BELITUNG" : bangka_belitung_urls,
    "GORONTALO" : gorontalo_urls,
    "DKI JAKARTA" : dki_jakarta_urls,
    "JAWA BARAT" : jawa_barat_urls,
    "BANTEN" : banten_urls,
    "JAWA TENGAH" : jawa_tengah_urls,
    "DI YOGYAKARTA" : yogyakarta_urls,
    "JAWA TIMUR" : jawa_timur_urls,
    "BALI" : bali_urls,
    "NUSA TENGGARA BARAT" : nusa_tenggara_barat_urls,
    "NUSA TENGGARA TIMUR" : nusa_tenggara_timur_urls,
    "KALIMANTAN BARAT" : kalimantan_barat_urls,
    "KALIMANTAN SELATAN" : kalimantan_selatan_urls,
    "KALIMANTAN TENGAH" : kalimantan_tengah_urls,
    "KALIMANTAN TIMUR" : kalimantan_timur_urls,
    "KALIMANTAN UTARA" : kalimantan_utara_urls,
    "SULAWESI SELATAN" : sulawesi_selatan_urls,
    "SULAWESI UTARA" : sulawesi_utara_urls,
    "SULAWESI TENGGARA" : sulawesi_tenggara_urls,
    "SULAWESI TENGAH" : sulawesi_tengah_urls,
    "SULAWESI BARAT" : sulawesi_barat_urls,
    "MALUKU" : maluku_urls,
    "MALUKU UTARA" : maluku_utara_urls,
    "PAPUA" : papua_urls,
    "PAPUA BARAT" : papua_barat_urls,
}