# Generated by Django 4.2.3 on 2024-02-29 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='name',
            new_name='title',
        ),
    ]
